### ISSUE TITLE
Use an ingress controller

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#10]
Instead of creating a `Service` with `type: LoadBalancer` on it for the interceptors, use a single ingress controller (it should be installed by the helm chart) and create an `Ingress` for each new app.

### Use-Case

Users should be able to use their existing ingress controller and have the operator integrate with it. Three use cases:

- A user has a brand new, vanilla k8s cluster and wants to install an ingress controller. they `helm install` the chart and the operator spits out `Ingress` resources
- A user has already installed the chart on their cluster and wants to reuse their existing ingress controller, so they `helm install` the chart and turn off the ingress controller option. the operator still spits out `Ingress` resources and the existing ingress controller picks them up properly
- A user has a new k8s cluster on their cloud provider, which has a built-in ingress controller, so they `helm install` the chart and the operator spits out `Ingress` objects and the cloud provider ingress picks them up properly

### Specification

- The helm chart should deploy an ingress controller
    - Have the helm chart take a dependency on the nginx ingress controller chart
    - Allow users to override that dependency, or turn it off completely if they already have one
- The operator should deploy `Ingress` objects

**Comment by arschles** [comment]
cc/ @khaosdoctor

**Comment by khaosdoctor** [comment]
Needs #36 for the annotations, I'm on it after that because it'll need some changes on the CRD api

**Comment by arschles** [comment]
closing, as this is out of scope
