### ISSUE TITLE
Provide support for scaling from 0 -> n and vice versa

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/http-add-on#101]
Provide support for scaling from `0 -> n` and vice versa s that KEDA handles everything rather than just activation.

This should follow the KEDA core approach where it can create an HPA for the user or fully rely on external push.

**Comment by arschles** [comment]
@tomkerkhove I'm not 100% sure what you mean here. Can you elaborate on "everything rather than just activation"

**Comment by tomkerkhove** [comment]
Doing more than 0->1 and 1-> but like we've chatted you are already building this :)

**Comment by arschles** [comment]
so @tomkerkhove #85 added minimum and maximum replicas but beyond that, I think we need to specify the use case(s) more precisely. can you elaborate?
