### ISSUE TITLE
Walkthrough Error: the path "examples/v0.8.0/httpscaledobject.yaml" does not exist

### ISSUE THREAD

**Issue by ImIOImI** [kedacore/http-add-on#1026]
### Report

The [documentation on the walkthrough](https://github.com/kedacore/http-add-on/blob/main/docs/walkthrough.md) isn't correct. It presupposes a manifest being located at `examples/v0.8.0/httpscaledobject.yaml` exists, but doesn't. Furthermore, the httpscaledobject is installed in the previous step with the xkcd application

### Expected Behavior

I should be able follow the walkthrough and successfully setup the xkcd application without getting any errors.

### Actual Behavior

When running `kubectl create -n $NAMESPACE -f examples/v0.8.0/httpscaledobject.yaml` I get the following error:
`the path "examples/v0.8.0/httpscaledobject.yaml" does not exist`

### Steps to Reproduce the Problem

Follow [the steps in the walkthrough](https://github.com/kedacore/http-add-on/blob/main/docs/walkthrough.md)

### Logs from KEDA HTTP operator

N/A

### HTTP Add-on Version

0.8.0

### Kubernetes Version

1.28

### Platform

Microsoft Azure

**Comment by JorTurFer** [comment]
Hello,
You're totally right, we didn't upgraded the example by mistake, let me open a PR with the fix

**Comment by JorTurFer** [comment]
These are the required changes, thanks for reporting it 😄 
https://github.com/kedacore/http-add-on/pull/1032
