### ISSUE TITLE
OTEL Env vars don't respect spec

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/http-add-on#1031]
### Report

We have merged the support for OTEL metrics, but the envs used don't respect the spec:
https://opentelemetry.io/docs/specs/otel/protocol/exporter/

### Expected Behavior

We should respect the spec, we use `KEDA_HTTP_OTEL_HTTP_COLLECTOR_ENDPOINT` when it should be `OTEL_EXPORTER_OTLP_ENDPOINT` (and probably supported automatically under the hood), or `KEDA_HTTP_OTEL_HTTP_COLLECTOR_INSECURE` instead of `OTEL_EXPORTER_OTLP_INSECURE` and other cases

**Comment by zorocloud** [comment]
Happy to align these if someone isn't already working on this issue.

**Comment by JorTurFer** [comment]
Thanks a lot ❤️

**Comment by zorocloud** [comment]
PR raised @JorTurFer. Shout if I've missed anything :slightly_smiling_face:.
