### ISSUE TITLE
Deploy helm charts to a repository

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#104]
Currently, we just instruct people to install from source. It would be nicer and more convenient to deploy charts to a helm repo so that we can instruct people to install without making them check out the code first.

### Use-Case

Instead of requiring folks to `git clone https://github.com/kedacore/http-add-on.git` before they run a `helm install`, I'd like folks to be able to run a `helm repo add` and then `helm install`. This allows users and operators to use the add on without interacting with the code at all.

We may consider putting charts inside of https://github.com/kedacore/charts, or hosting them with [artifact hub](https://artifacthub.io)

### Specification

- [ ] Install instructions should look similar to the ones in the [keda core ones](https://keda.sh/docs/2.1/deploy/#install)

**Comment by tomkerkhove** [comment]
Let's put them in https://github.com/kedacore/charts to consolidate them, they will then show up on artifact hub as well.

**Comment by arschles** [comment]
@tomkerkhove I'll submit a PR to kedacore/charts then. 👍

**Comment by arschles** [comment]
Going to do this after #78 is complete, since that includes a fairly large chart change

**Comment by khaosdoctor** [comment]
Took the time to do it today! Take a look at #125 please

**Comment by khaosdoctor** [comment]
This one could be closed I think. #125 is a bit stuck
