### ISSUE TITLE
Multiple deployments/stses auto scalating to one by http add on trigger

### ISSUE THREAD

**Issue by metsoft68** [kedacore/http-add-on#1081]
### Proposal

Adding support for multiple scaleTargetRef entries in the HTTP scale object manifest. Only one of these targets should be flagged as the primary, which the HTTP interceptor will proxy the request to. The non-primary targets should simply scale to 1. If a scaleTargetRef is referenced by another HTTP scale object, they should not conflict with each other.

### Use-Case

I have a testing/staging environment with around 20 microservices, 3 of which have ingress controllers that accept HTTP requests from outside. My goal is to scale all deployments, stateful sets, etc., to 1 based on the very first request that comes in via any of those 3 applications, using an HTTP scale object. This approach can significantly reduce costs for my test environments. Additionally, all pods should scale to 0 if none of those 3 ingresses have any traffic.

### Is this a feature you are interested in implementing yourself?

No

### Anything else?

keep up rocking! :)

**Comment by EinavDanielDX** [comment]
I have a similar use case, this feature would be most useful.

**Comment by nyobe** [comment]
I think that if #1083 were fixed this would be possible by creating multiple ScaledObjects that reference the same HTTPScaledObject trigger.
