### ISSUE TITLE
Ability to configure the targetPort of the interceptor-proxy service to have it listen on priviledged port 80

### ISSUE THREAD

**Issue by thomasfroehle** [kedacore/http-add-on#1111]
### Proposal

**Feature request:** 
Ability to configure the targetPort of the interceptor-proxy service to have it listen on port 80

**Workarounds:**
1) Set the interceptor.proxy.port to 80 and run the container as root
2) Patch the targetPort after helm install

### Use-Case

I would like the interceptor proxy service to listen on port 80 to avoid the need to change existing urls. These urls are now pointing via an ExternalName-Service to the keda-interceptor-proxy

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by JorTurFer** [comment]
Hello,
I guess that we could use different values for each usage, but we need to keep the current behavior as default. I mean, if the new value isn't given, we should use the current one
