### ISSUE TITLE
Walkthrough not working on k8s 1.19.3

### ISSUE THREAD

**Issue by relferreira** [kedacore/http-add-on#113]
I'm trying to recreate the walkthrough but without success. The operator was installed, but after creating the `HTTPScaledObject` the `keda-http-addon-controller-manager` could not create the proxy service.

Thanks a lot for this project, it is exactly what I was looking for.

Sorry if this error was already discussed.

## Expected Behavior
`keda-http-addon-controller-manager` should have created the `*-interceptor-proxy` service

## Actual Behavior
After creating the following `HTTPScaledObject` from the example:
```yaml
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: xkcd
spec:
    scaleTargetRef:
        deployment: xkcd
        service: xkcd
        port: 8080
    replicas:
        min: 5
        max: 10

```

The `keda-http-addon-controller-manager` is returning the following error:
```sh
2021-03-25T23:30:27.611Z	INFO	controllers.HTTPScaledObject	Reconciliation start	{"HTTPScaledObject.Namespace": "keda", "HTTPScaledObject.Name": "xkcd"}
2021-03-25T23:30:27.611Z	INFO	controllers.HTTPScaledObject	Adding Finalizer for the ScaledObject	{"HTTPScaledObject.Namespace": "keda", "HTTPScaledObject.Name": "xkcd"}
2021-03-25T23:30:27.619Z	ERROR	controllers.HTTPScaledObject	Failed to update HTTPScaledObject with a finalizer	{"HTTPScaledObject.Namespace": "keda", "HTTPScaledObject.Name": "xkcd", "finalizer": "httpscaledobject.http.keda.sh", "error": "HTTPScaledObject.http.keda.sh \"xkcd\" is invalid: spec.scaleTargetRef: Required value"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
github.com/kedacore/http-add-on/operator/controllers.ensureFinalizer
	/go/src/github.com/kedahttp/http-add-on/operator/controllers/finalizer.go:29
github.com/kedacore/http-add-on/operator/controllers.(*HTTPScaledObjectReconciler).Reconcile
	/go/src/github.com/kedahttp/http-add-on/operator/controllers/httpscaledobject_controller.go:112
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.1/pkg/internal/controller/controller.go:297
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.1/pkg/internal/controller/controller.go:252
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.1/pkg/internal/controller/controller.go:215
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
	/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99
```

## Steps to Reproduce the Problem

  1. Just followed the [walkthrough](https://github.com/kedacore/http-add-on/blob/main/docs/walkthrough.md)

## Specifications

  - **KEDA Version: 2.0.0
  - **Platform & Version: Azure AKS
  - **Kubernetes Version: 1.19.3
  - **Scaler(s): v0.0.1

**Comment by relferreira** [comment]
Sorry, I think I'm using an older version then the one described in the docs.
I couldn't find the latest commit in the package registry. Where can I pull it?

Thanks again.

**Comment by arschles** [comment]
@relferreira sorry I missed this - looks like for some reason it got closed before I saw it in my notifications! the latest official releases are are below:

- [scaler](https://github.com/orgs/kedacore/packages/container/http-add-on-scaler/1082285?tag=v0.0.1)
- [operator](https://github.com/orgs/kedacore/packages/container/http-add-on-operator/1082287?tag=v0.0.1)
- [interceptor](https://github.com/orgs/kedacore/packages/container/http-add-on-interceptor/1082278?tag=v0.0.1)

Also, it looks like we have an issue pushing to the GH package registry at the moment (https://github.com/kedacore/http-add-on/issues/147) - we're gonna be looking at that now. Thanks for catching it!
