### ISSUE TITLE
Make image pull policy configurable on helm chart

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#115]
Right now, it's hard-coded to `Always`. We should make that configurable.

### Use-Case

Some folks might rather not always re-pull images, especially for the scaler and interceptor, which might be spinning up and down repeatedly, if they add more apps or, in the case of the interceptor, traffic increases happen.

### Specification

- [ ] A new value is in `values.yaml` called `operator.pullPolicy` that parameterizes the operator's pull policy
- [ ] The operator has a new env var called `INTERCEPTOR_PULL_POLICY` that controls the interceptor's pull policy when the operator creates it
- [ ] Similarly, the operator has a `SCALER_PULL_POLICY` that controls the scaler's pull policy

**Comment by arschles** [comment]
@khaosdoctor would you be up for either integrating this into #125, or doing it in a follow up?

**Comment by khaosdoctor** [comment]
Sure thing, I think I can do it following up to make things separated.

**Comment by arschles** [comment]
Thank you! Up to you which you decide to do 👍

**Comment by khaosdoctor** [comment]
Already did it along because it was taking a while, so I wanted to close all possible issues

**Comment by khaosdoctor** [comment]
Now I just need to set it up on the operator
