### ISSUE TITLE
Provide detailed information when doing `get httpscaledobject`

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/http-add-on#119]
Provide detailed information when doing `get httpscaledobject` similar to KEDA core.

**Comment by arschles** [comment]
@tomkerkhove I'm assuming you mean fields like [these](https://github.com/kedacore/keda/blob/main/api/v1alpha1/scaledobject_types.go#L9-L20)? I'll submit a PR for this today so you can take a look.

**Comment by tomkerkhove** [comment]
Sounds good, thanks!
