### ISSUE TITLE
Create a dev container 

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#120]
VS Code [dev containers](https://code.visualstudio.com/docs/remote/create-dev-container) are a technology that let us define and use a docker container for the development environment.

### Use-Case

Setting up the development environment for the HTTP add has a few steps including setting up Go and kubebuilder, so it would be really useful to pre-configure this with a `Dockerfile` and define a dev container using that. It would save contributors a non-trivial amount of setup time.

### Specification

- [ ] Create a `.devcontainer` directory with a `Dockerfile` and `devcontainer.json` file in it. These should be set up properly for a dev container

**Comment by khaosdoctor** [comment]
Taking on this one

**Comment by arschles** [comment]
hasn't been much interest on this one, so I'm going to close. if anyone would like to see this, PRs are still welcome, or feel free to open a new issue.
