### ISSUE TITLE
Release: v0.9.0

### ISSUE THREAD

**Issue by wozniakjan** [kedacore/http-add-on#1221]
This issue template is used to track the rollout of a new KEDA HTTP add-on version.

For the full release process, we recommend reading [this document]([https://github.com/kedacore/keda/blob/main/RELEASE-PROCESS.md](https://github.com/kedacore/http-add-on/blob/main/RELEASE-PROCESS.md)).

## Required items

- [ ] https://github.com/kedacore/http-add-on/issues/1213
- [ ] bump KEDA v2.16.1

# Timeline

We aim to release this release in the week of December, 23. - 29, right after KEDA v2.16.1 is released.

## Progress

- [x] Add the new version to GitHub Bug report template
- [x] Create KEDA release
- [x] Prepare & ship Helm chart
- [x] Publish on Artifact Hub ([repo](https://github.com/kedacore/external-scalers))
- [x] Provide update in Slack
- [x] Tweet about new release

**Comment by JorTurFer** [comment]
Slack -> https://kubernetes.slack.com/archives/CKZJ36A5D/p1735322501056629
Twitter -> https://x.com/kedaorg/status/1872705514817372410
