### ISSUE TITLE
SHA / canary images are not getting pushed to GH container registry

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#147]
[Here](https://github.com/kedacore/http-add-on/runs/2398479931#step:6:148) is an example

## Expected Behavior

Each commit to `main` pushes a `sha-$GIT_SHA` image to GHCR and pushes a new `canary` tag

## Actual Behavior

See the failure linked above

## Steps to Reproduce the Problem

  1. Push to `main`
  2. Observe the canary GH action fail

**Comment by arschles** [comment]
This is still broken. Looks like we need to open access for the `GITHUB_TOKEN` to write to GHCR. See https://github.blog/changelog/2021-03-24-packages-container-registry-now-supports-github_token/

**Comment by tomkerkhove** [comment]
Done

**Comment by arschles** [comment]
Thanks!
