### ISSUE TITLE
Setting a dynamic target metric size

### ISSUE THREAD

**Issue by ajanth97** [kedacore/http-add-on#159]
### Why this is necessary
Currently the target metric is hardcoded at 100, as a result the scaling up happens quite slowly and the ratio of the **Number of pods** : **Load (Number of concurrent requests)** is quite low which leads to fewer pods available to handle the traffic. This could lead to lower TPS and higher latency on a service.  

### Load test results
I ran a load test using Jmeter on a simple echo service application. I have compared both autoscaling this service with the KEDA HTTP Add-on scaler and the KEDA Prometheus scaler.
Here are the results : https://docs.google.com/spreadsheets/d/1U5WDtUVp7SScKuaHsW7pBkPuIPXvWXqOR-WUGJSFEoI/edit?usp=sharing

### Discussion 
Link to discussion [here](https://github.com/kedacore/http-add-on/discussions/142)

**Comment by arschles** [comment]
thank you @ajanth97 for doing this investigation! I left a comment [in the discussion](https://github.com/kedacore/http-add-on/discussions/142#discussioncomment-695129)

**Comment by arschles** [comment]
@ajanth97 is this now done?
