### ISSUE TITLE
Write documentation for doing local testing

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#160]
Something like:

- build and push the images with mage
- `helm install` into your cluster
- use k9s and hey to do load testing

Put this into `contributing.md` probably

**Comment by arschles** [comment]
@Ritikaa96 nobody is working on it as far as I know, so please go ahead if you'd like. Ideally, they would walk a reader through how to set up one, two or all three of the components (as appropriate) to run successfully outside of a cluster.

**Comment by Ritikaa96** [comment]
Hi @arschles , I have added the documentation in [here](https://github.com/Ritikaa96/http-add-on/blob/local-testing-http-addon/CONTRIBUTING.md#locally-build--deploy-keda-http-addon). Please have a look and let me know if there is anything to change.

**Comment by Ritikaa96** [comment]
Just a gentle reminder @arschles @tomkerkhove PTAL at this:

> Hi @arschles , I have added the documentation in [here](https://github.com/Ritikaa96/http-add-on/blob/local-testing-http-addon/CONTRIBUTING.md#locally-build--deploy-keda-http-addon). Please have a look and let me know if there is anything to change or I'll raise a PR as soon as I get your go-ahead.

**Comment by tomkerkhove** [comment]
I think that's a good start, thank you! Any comments from your side @asw101?

**Comment by Ritikaa96** [comment]
@tomkerkhove should i raise a PR then? @asw101 @arschles PTAL

**Comment by tomkerkhove** [comment]
Certainly, thank you!
