### ISSUE TITLE
runtime.Object is nil error on the logs of the interceptor pod

### ISSUE THREAD

**Issue by ajanth97** [kedacore/http-add-on#174]
2021/06/02 16:31:35 Interceptor started, forwarding to service bal-test:80, watching deployment bal-test
2021/06/02 16:31:35 proxy server starting on 0.0.0.0:8091
2021/06/02 16:31:35 admin server running on 0.0.0.0:8090

   ____    __
  / __/___/ /  ___
 / _// __/ _ \/ _ \
/___/\__/_//_/\___/ v4.2.2
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
                                    O\
⇨ http server started on [::]:8090
panic: interface conversion: runtime.Object is nil, not *v1.Deployment

goroutine 38 [running]:
github.com/kedacore/http-add-on/pkg/k8s.NewK8sDeploymentCache.func1(0x16ccc78, 0xc0003765c0, 0xc0004a2ff0)
	/go/src/github.com/kedahttp/http-add-on/pkg/k8s/deployment_cache.go:60 +0x226
created by github.com/kedacore/http-add-on/pkg/k8s.NewK8sDeploymentCache
	/go/src/github.com/kedahttp/http-add-on/pkg/k8s/deployment_cache.go:52 +0x359

**Comment by arschles** [comment]
@ajanth97 thanks for finding/reporting this! I think the error comes from [here](https://github.com/kedacore/http-add-on/blob/main/pkg/k8s/deployment_cache.go#L60), where we're not checking if the type assertion worked. In fact, we're doing a similar thing here: https://github.com/kedacore/http-add-on/blob/main/interceptor/forward_wait_func.go#L41. In the latter case. I'll submit a PR to fix both.

**Comment by ajanth97** [comment]
@arschles thank you, will look into this shortly
