### ISSUE TITLE
Failed to pull operator image when using Helm

### ISSUE THREAD

**Issue by hieumoscow** [kedacore/http-add-on#187]
ImagePullBackOff issue after installing `kedacore/keda-add-ons-http` char

## Expected Behavior

K8s able to pull

## Actual Behavior

```Warning  Failed     35m (x4 over 37m)      kubelet            Failed to pull image "ghcr.io/kedacore/http-add-on-operator:vv0.1.0-v1alpha1": rpc error: code = Unknown desc = Error response from daemon: name unknown```

## Steps to Reproduce the Problem
`helm install http-add-on kedacore/keda-add-ons-http` or ` helm install http-add-on kedacore/keda-add-ons-http --set images.tag=latest` both produces the same result. It seems chart version **0.0.1** is stale (released by a previous pipeline where it adds an extra v in the tag) and needs to be updated

## Specifications

  - **KEDA Version:** *2.3.2*
  - **Platform & Version:** *0.0.1*
  - **Kubernetes Version:** *1.18.10*
  - **Scaler(s):** *http-add-on*

**Comment by tomkerkhove** [comment]
Thanks for reporting! What Helm registry did you use?

**Comment by blackmann** [comment]
Workaround is to edit the deployment and provide the latest version from here [](https://github.com/kedacore/http-add-on/pkgs/container/http-add-on-operator) using:

`kubectl edit deployment keda-add-ons-http-controller-manager`

**Comment by hieumoscow** [comment]
Hi @tomkerkhove, it was from the kedacore charts repo.
```bash
helm repo add kedacore **https://kedacore.github.io/charts**
helm install http-add-on kedacore/keda-add-ons-http
```

**Comment by tomkerkhove** [comment]
I Will take a look at it, thanks!

**Comment by hieumoscow** [comment]
In addition, when I tried to install the chart from the cloned **charts** repo.  It also faced the same error as the published tag is [v0.0.1](https://github.com/kedacore/http-add-on/pkgs/container/http-add-on-operator/versions), whereas the `default .Chart.AppVersion` is [0.0.1](https://github.com/kedacore/charts/blob/b2b469c22a542de95a5d151888ac2d1ca5980a9e/http-add-on/Chart.yaml#L23).

Thanks for the prompt response @tomkerkhove

**Comment by tomkerkhove** [comment]
@arschles What's the roadmap for v0.1.0? Are we shipping this week? Because this will be fixed in v0.1.0.

**Comment by arschles** [comment]
@tomkerkhove we can do 0.1.0 any time. I had to miss the developer meeting this morning, but I was going to get final sign-off on the release then.

**Comment by arschles** [comment]
@tomkerkhove looks like this is not fixed in 0.1.0 yet. We'll need https://github.com/kedacore/charts/pull/163 to be merged

**Comment by tomkerkhove** [comment]
It is not because of the missing chart or because it's still not fixed?

**Comment by arschles** [comment]
@tomkerkhove it is now fixed :) [here](https://github.com/kedacore/http-add-on/pkgs/container/http-add-on-operator/3390422) is the `0.1.0` operator image. I am closing this issue. @hieumoscow can you please open a new issue if you encounter the problem again?
