### ISSUE TITLE
Make the operator "maintain" all the app resources it creates

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#20]
Currently if you create an `HTTPScaledObject`, the operator will create a bunch of Kubernetes resources to encompass the "app" - things like `Service`s, `Deployment`s, `ScaledObject`s...

If you delete one of those resources, though, the app won't work properly and the operator isn't aware of that. When you go to delete or edit (https://github.com/kedacore/http-add-on/issues/7) the app, the resource just won't be there and the operator will just fail silently (on deletes, it just logs the missing resource and moves on).

It would be most helpful for the operator to somehow ensure the resources don't get deleted. I think this could be done with a finalizer on each of them.

### Use-Case

I'd like to more tightly "tie" the app resources to the `HTTPScaledObject` that caused them to be created, so that:

- Resources are more difficult to delete without also deleting the `HTTPScaledObject`
- If a resource is deleted, the operator will know about it and can (theoretically) re-create it

### Specification

- [ ] Demand #1

**Comment by khaosdoctor** [comment]
I think this one can be closed too, @arschles. Since #35 will modify the default way to use the add-on, it will not be needed to maintain created resources except for the ScaledObject

**Comment by tomkerkhove** [comment]
It will still have to maintain the ScaledObject and the interceptor service, thought.

**Comment by arschles** [comment]
As of now, it will still need to maintain the `ScaledObject` that it creates.
