### ISSUE TITLE
Not scaling to 0 

### ISSUE THREAD

**Issue by ajanth97** [kedacore/http-add-on#214]
## Expected Behavior
Scale to 0 when there is no traffic in the HTTP Request queue
## Actual Behavior
Always at a minimum of 1 replica
## Steps to Reproduce the Problem

I discussed with @arschles and @khaosdoctor about this problem and based on our investigations this behavior is caused by the following:

https://github.com/kedacore/http-add-on/blob/main/scaler/handlers.go#L33-L40

The `isActive` method here always returns `true`. Based on this bool KEDA scales to and from 0. If it true we scale from 0 to 1 and if its false the vice-versa.

**Comment by arschles** [comment]
@ajanth97 are you wanting #206 to fix this issue?

**Comment by ajanth97** [comment]
> @ajanth97 are you wanting #206 to fix this issue?

Yes I'd love to work on the fix.

**Comment by arschles** [comment]
@ajanth97 wonderful. care to do it as a branch off of #206? that PR will change a lot of code, so it would likely be more efficient to do it that way

**Comment by ajanth97** [comment]
Sure will make the change in a new branch
