### ISSUE TITLE
Send metrics to scaler to avoid latency in cold start

### ISSUE THREAD

**Issue by benjaminhuo** [kedacore/http-add-on#219]
I can see from the code that the scaler will pull the metrics every 500 ms to determine whether to scale.

https://github.com/kedacore/http-add-on/blob/main/scaler/queue_pinger.go#L49
https://github.com/kedacore/http-add-on/blob/main/scaler/main.go#L40
It’s hardcoded in the http-add-on’s source code to 500ms

This could introduce inevitable latency when scaling up from 0 

what I can see from knative's design doc is like below:

```
Unlike the queue-proxy, the activator actively sends metrics to the autoscaler via a websocket connection to minimize scale-from-zero latencies as much as possible.
```
It'll greatly reduce the latency of cold start if keda HTTP addon could introduce something similar to this mechanism.

https://github.com/knative/serving/blob/main/docs/scaling/SYSTEM.md

**Comment by arschles** [comment]
@benjaminhuo is the push interface described in https://github.com/kedacore/http-add-on/issues/97 suitable to achieve this?

**Comment by benjaminhuo** [comment]
@arschles Yeah, exactly. I can see the external push interface is marked as unimplemented in keda-http-addon.
It'll be great to have this added!

**Comment by arschles** [comment]
wonderful. stay tuned on #97. we'll likely start working on it shortly after the big #206 is merged and released
