### ISSUE TITLE
Have interceptors record what routing table version(s) they are aware of

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#225]
In #206, interceptors have to stay up to date on a namespace-global routing table. It would be helpful to provide a way for interceptors to confirm that they have gotten a specific version of the routing table.

### Use-Case

I imagine the most common use case for this functionality would be to ensure that all interceptors are aware of the most up to date routing table.

### Specification

The implementation can vary, but I can think of a few possible and feasible user interfaces:

- Have all interceptors write to some Kubernetes object indicating what version of the routing table they are currently aware of. We may find value in having them append to the object so that some observer can see history of each observer. 
    - One possible negative to this approach is that there may be a significant amount of garbage generated as changes to the routing table mount, and as interceptors come and go
- Expose an RPC endpoint on all interceptors that indicates what version they are aware of (and possibly a history of all versions they've been aware of, again for debuggability).
    - To fetch the currently-known versions of all interceptors, an observer would fetch the endpoints for the interceptor's admin `Service`, then issue the RPC to each interceptor. The scaler currently does something similar with `/queue` endpoints.

Note that since the routing table is stored in a `ConfigMap`, the aforementioned version numbers can be the same thing as the Kubernetes resource version.

cc/ @yaron2 since this is related to #206 and #183

**Comment by khaosdoctor** [comment]
I think the easiest way to do this is to have a simple endpoint on the admin server that will just echo the configMap resource version the interceptor has. The operator can compare that to the latest one fetched from the configMap itself and request an update if needed (there would be the need of an endpoint for that too)

**Comment by arschles** [comment]
@khaosdoctor, that would be the second bullet, correct?

**Comment by khaosdoctor** [comment]
Yep, just agreeing with that haha

**Comment by arschles** [comment]
perfect - just wanted to make sure we're on the same page. after #206 (which I'm planning on merging very soon) are you interested in taking this one on?
