### ISSUE TITLE
Interceptor holds request for a long time on scale-from-zero request

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#235]
In #206, the behavior of scale-from-zero requests is slightly changed and the interceptor no longer forwards requests properly when an app scales from zero up to >1

## Expected Behavior

The request is forwarded quickly after the pod is scaled up from zero.

## Actual Behavior

The request is held indefinitely.

## Steps to Reproduce the Problem

1. Scale an app to zero
1. Issue an HTTP request to the interceptor 
1. Observe that the interceptor holds the request indefinitely

**Comment by ajanth97** [comment]
Yes I have experienced this with the new multi-tenant interceptor. Any ideas ?

**Comment by arschles** [comment]
not sure yet, but working on it in #206

**Comment by ajanth97** [comment]
Great ill try to look too at what part of the interceptor is causing this behaviour

**Comment by arschles** [comment]
@ajanth97 I think I've found the culprit! https://github.com/kedacore/http-add-on/blob/a0a7969a6db3569151227c771f1657310e541f0d/pkg/k8s/deployment_cache.go#L56

I'm going change this channel receive to happen in a `select` and add some additional `case` statements in that `select` to:

- watch for the context cancellation/timeout: `case <-ctx.Done(): // cancel the goroutine here`
- periodically fetch the entire list of deployments, merge it into the internal `latestEvts` map, and broadcast events

**Comment by ajanth97** [comment]
Nice, Well done !

**Comment by arschles** [comment]
This was introduced and fixed in #206. Closing
