### ISSUE TITLE
Add TODO bot to this repository

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#239]
https://github.com/apps/todo

**Comment by tomkerkhove** [comment]
I'm using https://github.com/marketplace/check-todo but can add that one for you if you want.

**Comment by tomkerkhove** [comment]
Ha this one creates issues, ok. let me know if I have to add it.

**Comment by arschles** [comment]
@tomkerkhove the check-todo one sounds good to me since you're using it already. it looks like I'm unable to add it, so yes, can you please add that one?

**Comment by tomkerkhove** [comment]
Done!

**Comment by arschles** [comment]
Thanks @tomkerkhove !!
