### ISSUE TITLE
Add ability to debug outside cluster (Proposal)

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#244]
The ability to run one or more components on your local machine, outside a cluster, would ease debuggability for some folks. 

### Use-Case

A developer fixing a bug or building a feature might have an easier time making progress if they can simply `go run ./<component>` on their local machine and have that component hook directly up to the rest of the system running in a cluster. While there will be limitations to running the system with this arrangement, this feature has good potential to help developers. We will document those limitations well.

### Specification

Due to the way the system is architected, some functionality won't work depending on how exactly you set things up, and some things will need to be run together.

Components will add a new configuration parameter to indicate that they should run outside the cluster. When set, the component will fetch a `*rest.Config` from a local Kubernetes config file rather than use the in-cluster config. For example:

```go
if shouldRunOutsideCluster {
    config, err := clientcmd.BuildConfigFromFlags("", "~/.kube/config")
}
```

Also, since there is intra-cluster network communication from scaler to interceptor and interceptor to application `Service`, some of this communication won't work or will be limited. For example, since the scaler uses the interceptor's `Service` DNS name, the scaler would not be able to communicate with the interceptor if the former was running outside the cluster and the latter inside. We will document this and other similar scenarios, suggest that they be run together (both inside or both outside the cluster), and explain how to do that

**Comment by JorTurFer** [comment]
This is already supported
