### ISSUE TITLE
Interceptor and external scaler fails to fetch routing table config map

### ISSUE THREAD

**Issue by ajanth97** [kedacore/http-add-on#271]
There is an error when fetching the **routing table config map**

* Interceptor pod logs :

> {"level":"error","ts":1632831910.545934,"logger":"pkg.routing.GetTable","caller":"routing/config_map.go:115","msg":"failed to fetch routing table config map","configMapName":"keda-http-routing-table","error":"configmaps \"keda-http-routing-table\" not found","stacktrace":"github.com/kedacore/http-add-on/pkg/routing.GetTable\n\t/go/src/github.com/kedacore/http-add-on/pkg/routing/config_map.go:115\nmain.main\n\t/go/src/github.com/kedacore/http-add-on/interceptor/main.go:79\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}

* External Scaler pod logs : 

> {"level":"error","ts":1632832226.6490338,"caller":"scaler/main.go:99","msg":"one or more of the servers failed","error":"failed to fetch routing table: failed to fetch ConfigMap keda-http-routing-table: configmaps \"keda-http-routing-table\" not found","errorVerbose":"configmaps \"keda-http-routing-table\" not found\nfailed to fetch ConfigMap keda-http-routing-table\ngithub.com/kedacore/http-add-on/pkg/routing.GetTable\n\t/go/src/github.com/kedacore/http-add-on/pkg/routing/config_map.go:121\ngithub.com/kedacore/http-add-on/pkg/routing.StartConfigMapRoutingTableUpdater\n\t/go/src/github.com/kedacore/http-add-on/pkg/routing/config_map_updater.go:47\nmain.main.func2\n\t/go/src/github.com/kedacore/http-add-on/scaler/main.go:77\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nfailed to fetch routing table\ngithub.com/kedacore/http-add-on/pkg/routing.StartConfigMapRoutingTableUpdater\n\t/go/src/github.com/kedacore/http-add-on/pkg/routing/config_map_updater.go:48\nmain.main.func2\n\t/go/src/github.com/kedacore/http-add-on/scaler/main.go:77\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371","stacktrace":"main.main\n\t/go/src/github.com/kedacore/http-add-on/scaler/main.go:99\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}

## Specifications

- **KEDA Version:** 2.4.0 **
- **KEDA HTTP Add-on Version:** *0.1.0*
- **Platform & Version:** *AKS*
- **Kubernetes Version:** *1.19.11*

**Comment by arschles** [comment]
I think this is because the operator only adds the routing table `ConfigMap` when an `HTTPScaledObject` event happens. The result is that if you install the HTTP Addon on a brand new, never-been touched cluster, this failure will happen. I think the  operator should try to create the `ConfigMap` when it starts up, if the `ConfigMap` already exists, then the operator shouldn't fail though.

**Comment by ajanth97** [comment]
@arschles Yeah I think creating it from the charts will be better option since we can clean up the code in the operator.

**Comment by arschles** [comment]
@ajanth97 done. here is the commit for reference: https://github.com/kedacore/charts/pull/169/commits/512b7ef3d213f2475deedce4dddfd1dc39a13435
