### ISSUE TITLE
Interceptor timeout  

### ISSUE THREAD

**Issue by ajanth97** [kedacore/http-add-on#274]
Interceptor timesout and returns a 502 : 

> error on backend (context marked done while waiting for deployment go-echo to reach > 0 replicas (context deadline exceeded))

Interceptor logs : 

> {"level":"error","ts":1632921440.6612947,"logger":"runProxyServer","caller":"interceptor/proxy_handlers.go:77","msg":"wait function failed, not forwarding request","error":"context marked done while waiting for deployment go-echo to reach > 0 replicas (context deadline exceeded)","stacktrace":"main.newForwardingHandler.func1\n\t/go/src/github.com/kedacore/http-add-on/interceptor/proxy_handlers.go:77\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2049\nmain.countMiddleware.func1\n\t/go/src/github.com/kedacore/http-add-on/interceptor/middleware.go:48\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2049\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2867\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1932"}

## Specifications

- **KEDA Version:** *2.4.0*
- **KEDA HTTP Add-on Version:** *0.1.0*
- **Platform & Version:** *AKS*
- **Kubernetes Version:** *1.19.11*

**Comment by arschles** [comment]
This is fixed with https://github.com/kedacore/charts/pull/197. Closing
