### ISSUE TITLE
Proposal: forward request in interceptor even if wait func fails

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#276]
I believe that the wait function is useful so that the interceptor does not begin attempting to connect (and backing off on connections) to the application until it is sure that the application has scaled up to 1 or more replicas. In the case that the wait function fails, it might be useful for the interceptor to try to forward the request anyway, though.

### Use-Case

The interceptor is unable to communicate with Kubernetes, nor get any events from it. In this case, the application may still be running and the interceptor can still forward requests.

### Specification

If the `waitFunc()` call fails in the interceptor's proxy handler, it should still forward the request. Optional addition: in cases where the wait func has failed `N` times in the recent past (or some other similar metric), the interceptor should call the wait function and record its response, but not wait for it.

**Comment by ajanth97** [comment]
I agree somewhat but then the response of the request would be unpredictable. I personally think we should figure out a way that we can assure a deployment has more than 0 replicas

**Comment by arschles** [comment]
Agreed, the wait function needs to improve its reliability. That said, though, we need to plan for network and k8s control plane issues. I think eventually it will be important to build in fallback functionality to the interceptor so that requests still make it through, even if the control plane is inaccessible from the interceptor.

**Comment by ajanth97** [comment]
Agreed ! yeah let's do that. Let's forward the request to the relevant service and still log the error if the control plane is inaccessible.
