### ISSUE TITLE
Use client-go's informer to replace the custom routing table config map updater

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#287]
There are quite a few places where we have to consume a kubernetes resource, watch it for changes, and keep a copy of it (or some data derived from a copy of it) in memory and up-to-date. So far, we have written code from scratch that uses a `watch.Interface` to watch for changes, and uses a Kubernetes client to periodically do a full fetch of the Kubernetes resource(s) in question.

In #269, we're beginning to remove some of this custom code in favor of the [informer](https://pkg.go.dev/k8s.io/client-go@v0.22.2/informers) framework for the deployment cache. This issue is to replace all of the other appropriate instances of such code:

- Watching the routing table `ConfigMap` in the scaler
- Watching the routing table `ConfigMap` in the interceptor

### Use-Case

We will be able to delete a nontrivial amount of code by doing this work.

### Specification

- Refactor the code in `https://github.com/kedacore/http-add-on/blob/main/pkg/routing/config_map_updater.go` to use an informer rather than a custom-built `for` loop

**Comment by tpiperatgod** [comment]
I am interested in this matter, is it possible to assign it to me?

**Comment by arschles** [comment]
@tpiperatgod GitHub won't let me set the "assignee" field to you, but please feel free to work on it.

#269 will replace the deployment cache with the informer, so would you mind working on the routing table updater code?

**Comment by tpiperatgod** [comment]
I submitted a pr but still have some matters I would like to discuss with you:

> When the configmap named "keda-http-routing-table" changes (e.g., a new httpscaledobjects is created), the external-scaler service will request keda to access the IsActive rpc of the http-add-on in the external-push mode.
>
> However, since the [minimum resynchronization period](https://github.com/kubernetes/client-go/blob/v0.22.2/tools/cache/shared_informer.go#L475) of the informer is 1s, the IsActive rpc request launched by keda will fail in the first 1s (this has no effect on the subsequent functionality, but there will be error log output).
>
> Should we make StreamIsActive run after a 1 second delay? or just keep it.
>
> And according to the optimization for the external-scaler(and interceptor) mentioned at https://hackmd.io/ttpSY5KQQtGIqbAzyKex3g, it will also solve this problem I think.

**Comment by arschles** [comment]
@tpiperatgod I just reviewed your PR (#326) - thanks for submitting it. I answered your question [there](https://github.com/kedacore/http-add-on/pull/326#pullrequestreview-808945867), so let's discuss it there.
