### ISSUE TITLE
external scalar and interceptor pods are not created while deploying reference chart xkdc 

### ISSUE THREAD

**Issue by dheerajjoshim** [kedacore/http-add-on#310]
I am trying to deploy the reference helm chart of `xkdc` and `external-scalar` and `interceptor` pods are not created. Pod gets terminated. `
external-scaler`, `interceptor-admin `, and `interceptor-proxy` services are created momentarily and eventually get removed. 

## Expected Behavior
Deploying a helm chart should create `external-scalar` and `interceptor` pods and services. So these services could be called from the ingress resource. 

## Actual Behavior
No `external-scalar` and `interceptor` pods and services are created

## Steps to Reproduce the Problem
  1. Deploy Keda http-add-on onto keda namespace
  2. Deploy xkdc helm chart onto keda namespace
  3. Try to access ingress. Rather than getting 200 response we get 503 response
  4. Now list all K8S services in Keda namespace. `proxy`, `scalar` and other services are missing

## Specifications

- **KEDA Version:** *keda-2.4.0*
- **KEDA HTTP Add-on Version:** *keda-add-ons-http-0.1.0*
- **Platform & Version:** *minikube on mac - v1.23.2*
- **Kubernetes Version:** *1.22.2*

Logs from `http-add-on` pod

[logs from keda-add-ons-http-controller-manager pod](https://github.com/kedacore/http-add-on/files/7495749/logs-from-keda-add-ons-http-operator-in-keda-add-ons-http-controller-manager-ddfb976d5-9pqcs.log)

**Comment by arschles** [comment]
hi @dheerajjoshim - thanks for this. we are just about to release `v0.2.0` in the next few days, which should fix this issue. when it is released, would you mind installing the new version and re-testing?

**Comment by dheerajjoshim** [comment]
@arschles I would test this again with `v0.2.0` when it is released.

**Comment by arschles** [comment]
thanks @dheerajjoshim !

**Comment by arschles** [comment]
@dheerajjoshim [version `v0.2.0`](https://github.com/kedacore/http-add-on/releases/tag/v0.2.0) is now released. Can you try uninstalling your app and the HTTP Addon, and then re-installing everything?

**Comment by dheerajjoshim** [comment]
@arschles  Let me install the latest HTTP add-on and retest.

**Comment by dheerajjoshim** [comment]
With version `[v0.2.0](https://github.com/kedacore/http-add-on/releases/tag/v0.2.0)` everything seems to be working fine. Hence closing the ticket

**Comment by arschles** [comment]
Thank you for checking @dheerajjoshim. I'm glad it is working for you now.
