### ISSUE TITLE
Support Kubernetes Gateway APIs for Ingress

### ISSUE THREAD

**Issue by beriberikix** [kedacore/http-add-on#33]
The network SIG has been hard at work developing the new [Gateway API](https://gateway-api.sigs.k8s.io/), aka Ingress V2. A Gateway is responsible for routing a request to a service. There's already an HTTPRoute [implementation](https://kubernetes-sigs.github.io/service-apis/httproute/). The API has several [integration points](https://kubernetes-sigs.github.io/service-apis/api-overview/#extension-points) and I think the current Interceptor could be integrated or evolved to integrate with the existing HTTP implementation. Alternatively, a new [GatewayClass](https://kubernetes-sigs.github.io/service-apis/api-overview/#gatewayclass) can be designed to work specifically with KEDA and still make use of the standardized API.

Might relate to #10 and possibly #6. /cc folks from Services API who know way more than I do :) @hbagdi @jpeach @robscott

_Edit @tomkerkhove: Updated link given it was renamed to Gateway API._

**Comment by arschles** [comment]
@beriberikix sounds like it'd be useful to have the operate create service API resources instead of (in addition to?) plain old `Ingress` resources that #10 calls for.

Another aspect is metrics. We can do routing with this, but is there a standard metrics API that this comes with? SMI is certainly one solution but something designed explicitly for north-south traffic, as you said in today's meeting, could be more beneficial.

Looking forward to hearing your thoughts!

**Comment by tomkerkhove** [comment]
I think the same here @arschles - Folks should be able to choose if we manage it or they bring their own imo

**Comment by beriberikix** [comment]
💯! It's also entirely possible someone has a very custom Ingress solution and this shouldn't prevent them as well. Services API should be *in addition* to `Ingress` (and user choice which to instantiate), especially since Ingress V1 is currently the only GA supported way and Service API is still in Beta. 

@arschles great questions on Metrics. I've asked in #sig-network-service-apis channel for input!

**Comment by hbagdi** [comment]
> Service API is still in Beta.

nit: Service APIs (or Gateway API in future) is in alpha.

> It's also entirely possible someone has a very custom Ingress solution and this shouldn't prevent them as well. Services API should be in addition to Ingress

That's correct. Based on the community interest, it seems like most ingress controllers will add support for Service APIs in future. Ingress isn't going anywhere.

**Comment by beriberikix** [comment]
RE: metrics @robscott:

> There’s interest in this but it’s not a core priority. We’re trying to focus on getting all the core parts of the API right first but could eventually expand the scope to include this. This could be a good opportunity for an implementation to experiment with a potential spec for metrics and then work on upstreaming it if it works well.

**Comment by wozniakjan** [comment]
> Is there anything left?

I just need to find some time to finish https://github.com/kedacore/http-add-on/pull/1052, but after that imho not much left with the currently considered scope for both `Ingress` and `HTTPRoute`. Both are documented equally and will be covered by similar e2e tests.
