### ISSUE TITLE
Reset the number of replicas of the target deployment while deleting httpscaledobject

### ISSUE THREAD

**Issue by tpiperatgod** [kedacore/http-add-on#332]
## Expected Behavior
I expect to be able to reset the number of replicas of the target deployment while deleting the httpscaledobject resource.

## Actual Behavior
No one to manage the number of replicas of the target deployment after the httpscaledobject resource has been deleted.

## Steps to Reproduce the Problem

  1. Creating xkcd and xkcd httpscaledobject resource
  2. Use the command `hey -z 30s -c 800 'http://myhost.com'` to scale it to 8 replicas
  3. Delete xkcd httpscaledobject resource before xkcd's replicas down to 0
  4. The number of replicas of xkcd will remain at 8
  ```shell
    ~# kubectl get po -n keda
    NAME                                                    READY   STATUS    RESTARTS   AGE
    ingress-nginx-controller-5c8d66c76d-ztwpg               1/1     Running   0          15d
    keda-add-ons-http-controller-manager-55b7d5c77d-svc9n   2/2     Running   0          3d3h
    keda-add-ons-http-external-scaler-8898bcbdb-2nxnm       1/1     Running   0          3d3h
    keda-add-ons-http-interceptor-7894949fb5-jsltm          1/1     Running   0          3d3h
    keda-operator-5c569bb794-k59j9                          1/1     Running   0          7d23h
    keda-operator-metrics-apiserver-78f4f687dd-cgtbt        1/1     Running   0          15d
    xkcd-84459f7fbf-5hwq2                                   1/1     Running   0          4h35m
    xkcd-84459f7fbf-8jkb5                                   1/1     Running   0          4h35m
    xkcd-84459f7fbf-bdr46                                   1/1     Running   0          4h35m
    xkcd-84459f7fbf-plxfr                                   1/1     Running   0          4h35m
    xkcd-84459f7fbf-srsd4                                   1/1     Running   0          4h35m
    xkcd-84459f7fbf-thp6t                                   1/1     Running   0          4h35m
    xkcd-84459f7fbf-vrmql                                   1/1     Running   0          4h35m
    xkcd-84459f7fbf-zjzlp                                   1/1     Running   0          4h35m
  ```

## Specifications

- **KEDA Version:** *2.4.0*
- **KEDA HTTP Add-on Version:** *0.2.0.RC1*
- **Platform & Version:** *Ubuntu 18.04 LTS x86_64*
- **Kubernetes Version:** *v1.21.5*

Is it possible to add a parameter to do the job of resetting the number of replicas of the target deployment after deleting the hso? It would have the advantage of putting the target deployment back in a state where it can be expected.

Or is there actually a way to do this already?

Obviously, I may have missed the relevant problems about whether the connection will be interrupted. So, if you agree with the expectations I have raised, we can discuss how to implement it with the guarantee that access will not be interrupted.

**Comment by arschles** [comment]
@tpiperatgod since `KEDA` does the actual scaling, we could use that to achieve this. if the HTTP Addon operator created the `ScaledObject` with [`spec.advanced.restoreToOriginalReplicaCount`](https://github.com/kedacore/keda/blob/main/apis/keda/v1alpha1/scaledobject_types.go#L100) set to `true`, then when it later deletes that `ScaledObject`, KEDA would take care of restoring the `Deployment` to the original number of replicas. Does this solution sound like it would work for your use case?

Regarding connection interruptions, are you talking about just what happens when replicas are removed?

**Comment by tpiperatgod** [comment]
> @tpiperatgod since `KEDA` does the actual scaling, we could use that to achieve this. if the HTTP Addon operator created the `ScaledObject` with [`spec.advanced.restoreToOriginalReplicaCount`](https://github.com/kedacore/keda/blob/main/apis/keda/v1alpha1/scaledobject_types.go#L100) set to `true`, then when it later deletes that `ScaledObject`, KEDA would take care of restoring the `Deployment` to the original number of replicas. Does this solution sound like it would work for your use case?

This solution should work, I think.

> Regarding connection interruptions, are you talking about just what happens when replicas are removed?

I do mean this scenario. I would like to know if it is normal behavior for HTTP Addon to disconnect when deleting an HSO by default when `restoreToOriginalReplicaCount` is set to true?

**Comment by arschles** [comment]
>This solution should work, I think.

Great, it should be a pretty small change, then. Would you like to do it? If not, I'm happy to. Just let me know.

>I do mean this scenario. I would like to know if it is normal behavior for HTTP Addon to disconnect when deleting an HSO by default when restoreToOriginalReplicaCount is set to true?

Regarding connections, the interceptor is the key component here. When the HSO is deleted for a host, the interceptor should immediately stop routing _new_ incoming requests to the `Deployment` (because its routing table gets updated). Existing ones in-flight should get completed though. Are you seeing different behavior?

**Comment by tpiperatgod** [comment]
> Great, it should be a pretty small change, then. Would you like to do it? If not, I'm happy to. Just let me know.

Yes, I'd like to.

> Regarding connections, the interceptor is the key component here. When the HSO is deleted for a host, the interceptor should immediately stop routing _new_ incoming requests to the `Deployment` (because its routing table gets updated). Existing ones in-flight should get completed though. Are you seeing different behavior?

Thanks for the answer, I think I've understood.

**Comment by arschles** [comment]
>Yes, I'd like to.

That's great news. Feel free to submit a pull request whenever you'd like. I am happy to review it.
