### ISSUE TITLE
Set up CI & Push Images to GitHub Container Registry

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#34]
### Use-Case

Images for the interceptor, scaler and operator need to be pushed to somewhere. Right now, the Makefile hard-codes to push to `arschles/$WHATEVER`. Change that to push to the new GitHub container registry

### Specification

- [ ] Have GitHub Actions automatically run on pushes to `main`
- [ ] Have each run automatically push to the GH container registry

**Comment by khaosdoctor** [comment]
On it
