### ISSUE TITLE
Maintainers Time off (2021-12-17 - 2022-01-03)

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#344]
Hello All,

I will be taking time off for the end of the (Gregorian) calendar year. For much of the time between December 17, 2021 and January 3, 2022, I will be offline, so I won't be able to do most reviews nor comment on issues.

When I get back, I'll ensure that everything that needs my attention gets it! Also, I'll do my best before I leave to review and comment on everything that needs my attention.

Thanks everyone, and I'm looking forward to coming back in the new year!

**Comment by zroubalik** [comment]
Enjoy your time off @arschles!

**Comment by arschles** [comment]
thanks @zroubalik - I hope you do too!

**Comment by arschles** [comment]
I'm back and reviewing / working now. Thanks everyone for the good wishes and for waiting!
