### ISSUE TITLE
Add routing table lifecycle diagram to documentation

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#345]
@tpiperatgod created a great lifecycle diagram for the routing table in https://github.com/kedacore/http-add-on/pull/326#issuecomment-972946943. It would be very useful to add this diagram to documentation.

### Use-Case

I think this diagram would be very helpful especially for HTTP Addon developers looking to understand the system better. I bet it would also help operators trying to troubleshoot.

### Specification

The diagram should be added either to an existing document or added to a new one.

**Comment by JorTurFer** [comment]
This doesn't apply as we don't use the table any more
