### ISSUE TITLE
error on backend (net/http: timeout awaiting response headers)

### ISSUE THREAD

**Issue by avinash31d** [kedacore/http-add-on#369]
### Report

Facing error on backend (net/http: timeout awaiting response headers) on POST request with multipart form data.

### Expected Behavior

STATUS 200

### Actual Behavior

Facing error on backend (net/http: timeout awaiting response headers) on POST request with multipart form data while uploading a file 

### Steps to Reproduce the Problem

1. follow the docs ok xkcd app 
2. create a sample file upload service
3. upload a file using rest api client

### Logs from KEDA HTTP operator

[19/Jan/2022:10:02:06 +0000] "POST /process HTTP/1.1" 502 62 "-" "-" 725850 0.606 [keda-keda-add-ons-http-interceptor-proxy-8080] [] 10.244.0.27: │
│ 8080 62 0.508 502 fb44ddc51947ba816ffd65e113dc456f

**Comment by arschles** [comment]
@avinash31d I see that you opened and then closed this issue. Are you no longer seeing the problem?

**Comment by avinash31d** [comment]
@arschles I increased the timout value and it is working now.

**Comment by arschles** [comment]
ok, great. the timeout is fairly dependent on several details, including some details of your cluster, container sizes, and more. I'm glad you figured it out. There is a (now closed) issue that can give you some more details on this timeout, if you are interested: https://github.com/kedacore/http-add-on/issues/276

**Comment by paales** [comment]
I'm just trying out the http-add-on and a fairly newb when it comes to Kubernetes in general, but any pointers where one would configure this timeout?

**Comment by oliver-hofmann-cistec-com** [comment]
> I'm just trying out the http-add-on and a fairly newb when it comes to Kubernetes in general, but any pointers where one would configure this timeout?

https://keda.sh/docs/2.3/operate/cluster/
