### ISSUE TITLE
Http External Scaler failing

### ISSUE THREAD

**Issue by SteveRiceUK** [kedacore/http-add-on#424]
### Report

The Http external scaler pod continuously restarts every 10-15 minutes with the following error...
fatal error: concurrent map writes

This is with only one http scaled object configured.

Any help appreciated.

### Expected Behavior

Pod to continuously run.

### Actual Behavior

Pod continuously restarts.

### Steps to Reproduce the Problem

1.
2.
3.

### Logs from KEDA HTTP operator

	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc00046c880)
	/usr/local/go/src/internal/poll/fd_unix.go:402 +0x22c
net.(*netFD).accept(0xc00046c880)
	/usr/local/go/src/net/fd_unix.go:173 +0x35
net.(*TCPListener).accept(0xc00046e7c8)
	/usr/local/go/src/net/tcpsock_posix.go:140 +0x28
net.(*TCPListener).Accept(0xc00046e7c8)
	/usr/local/go/src/net/tcpsock.go:262 +0x3d
google.golang.org/grpc.(*Server).Serve(0xc000472a80, {0x1a18760, 0xc00046e7c8})
	/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:779 +0x362
main.startGrpcServer({0x1a1c038, 0xc000499380}, {{0x1a39b78, 0xc00046b260}, 0x1000000010000}, 0x0, 0xc00046c180, 0xc0004d2d00, 0x64, 0x1)
	/go/src/github.com/kedacore/http-add-on/scaler/main.go:166 +0x36e
main.main.func3()
	/go/src/github.com/kedacore/http-add-on/scaler/main.go:97 +0x73
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92

### What version of the KEDA HTTP Addon are you running?

0.3.0

### Platform

Amazon Web Services

**Comment by arschles** [comment]
Hi @SteveRiceUK - this was fixed in #414, but has not been released officially yet. Expect to see that fix in v0.4.0. Until then, you can use images tagged `canary` or `sha-2d35d0d` (see https://github.com/kedacore/http-add-on/issues/414#issuecomment-1075521557 for details).
