### ISSUE TITLE
error on backend (net/http: timeout awaiting response headers)

### ISSUE THREAD

**Issue by JieDing** [kedacore/http-add-on#432]
### Report

I am using http-add-on and creating a HTTPScaledObject successfully. The scaled deployment scales down to 0 at first. And once I curl the http-interceptor-proxy via ingress, it reported an error:
error on backend (net/http: timeout awaiting response headers)
but the container is scaled up to 1 successfully.
The weird thing is that, only the first curl will report this error, and other tries after the first curl can work well.
I tried several times, and every first curl (when the pod needs to activate from 0 to 1) will fail, while other curls after that can success.

### Expected Behavior

STATUS 200 and obtain http content from the deployment

### Actual Behavior

every first curl (when the pod needs to activate from 0 to 1) will fail, while other curls after that can success.

### Steps to Reproduce the Problem

1. helm install http-add-on kedacore/keda-add-ons-http
2. kubectl apply -f httpscaledobject.yaml (depolyment image is "tomcat:8.0.18-jre8")
3. helm install ingress-nginx ingress-nginx/ingress-nginx
4. create an ingress and point to keda-add-ons-http-interceptor-proxy service
5. curl -H "Host: myhost.com" <My IP>

NOTE: this error appears every time when the pod needs to activate from 0 to 1. It won't appear if the pod already has 1 replica.

### Logs from KEDA HTTP operator

```
example
```

### What version of the KEDA HTTP Addon are you running?

0.3.0

**Comment by tpiperatgod** [comment]
It commonly takes a long time for a workload to start up for the first time (i.e., from 0 to 1 replica), a process called **cold start**. This is probably the issue you are facing.

Perhaps you can try to solve this problem by adjusting the [timeout-related](https://github.com/kedacore/http-add-on/blob/v0.3.0/interceptor/config/timeouts.go#L11) parameters. Such as this parameter: https://github.com/kedacore/http-add-on/blob/v0.3.0/interceptor/config/timeouts.go#L18

**Comment by JieDing** [comment]
> Perhaps you can try to solve this problem by adjusting the [timeout-related](https://github.com/kedacore/http-add-on/blob/v0.3.0/interceptor/config/timeouts.go#L11) parameters. Such as this parameter: https://github.com/kedacore/http-add-on/blob/v0.3.0/interceptor/config/timeouts.go#L18

@tpiperatgod thx for your reply.
I tried to set the `responseHeaderTimeout` when I installed the keda-http-on :
`helm install http-add-on kedacore/keda-add-ons-http --set responseHeaderTimeout=5s`
Then I re-start the whole process again. This time when I curl the ingress controller for the first time, it errored again:
`error on backend (net/http: timeout awaiting response headers)`
And it absolutely didn't wait for 5 seconds. It just directly return this error within like 100ms.
Did I set the timeout right? or I have to set it in codes and re-build the interceptor?

**Comment by tpiperatgod** [comment]
Hi, @JieDing You can find these parameters in the deployment's configuration:

```shell
$ kubectl get deployments.apps -n ${NAMESPACE} keda-add-ons-http-interceptor -oyaml
...
    spec:
      containers:
      - env:
        - name: KEDA_HTTP_ROUTING_TABLE_UPDATE_DURATION_MS
          value: "500"
        - name: KEDA_HTTP_CURRENT_NAMESPACE
          value: keda
        - name: KEDA_HTTP_PROXY_PORT
          value: "8080"
        - name: KEDA_HTTP_ADMIN_PORT
          value: "9090"
        - name: KEDA_HTTP_CONNECT_TIMEOUT
          value: 500ms
        - name: KEDA_HTTP_KEEP_ALIVE
          value: 1s
        - name: KEDA_RESPONSE_HEADER_TIMEOUT
          value: 500ms
        - name: KEDA_CONDITION_WAIT_TIMEOUT
          value: 20s
        - name: KEDA_HTTP_DEPLOYMENT_CACHE_POLLING_INTERVAL_MS
          value: "250"
        - name: KEDA_HTTP_FORCE_HTTP2
          value: "false"
        - name: KEDA_HTTP_MAX_IDLE_CONNS
          value: "100"
        - name: KEDA_HTTP_IDLE_CONN_TIMEOUT
          value: 90s
        - name: KEDA_HTTP_TLS_HANDSHAKE_TIMEOUT
          value: 10s
        - name: KEDA_HTTP_EXPECT_CONTINUE_TIMEOUT
          value: 1s
...

```

Use the `kubectl edit` command to modify them directly to take effect. 

But I didn't reproduce the problem...🥲 So I'm not really sure if these parameters are relevant to the problem you are facing.

Perhaps you could post the configuration of all the deployments of `keda-add-ons-http-*`

**Comment by JieDing** [comment]
@tpiperatgod That does work dude! Thx so much for your patient help.

**Comment by arschles** [comment]
thanks @tpiperatgod !
