### ISSUE TITLE
Cannot pull ghcr.io images

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#48]
After https://github.com/kedacore/http-add-on/runs/1841953328?check_suite_focus=true, docker images should have been pushed to GH container registry. It appears from https://github.com/orgs/kedacore/packages that the images didn't get pushed at all, but running `docker pull` tells another story:

```shell
~ docker pull ghcr.io/kedacore/http-add-on-operator:sha-8c5a4c8
Error response from daemon: pull access denied for ghcr.io/kedacore/http-add-on-operator, repository does not exist or may require 'docker login': denied: permission_denied: read_package
```

I don't know how reliable that error message is, but I presume that it implies that anonymous read access is disabled.

## Expected Behavior

`docker pull ghcr.io/kedacore/http-add-on-operator:sha-8c5a4c8` should succeed, as should `docker pull ghcr.io/kedacore/http-add-on-operator:canary` should pass

## Actual Behavior

See failure above

## Steps to Reproduce the Problem

  1. Run `docker pull ghcr.io/kedacore/http-add-on-operator:sha-8c5a4c8`

**Comment by khaosdoctor** [comment]
I think the problem is that the personal access token generated did not include `package:read` permissions. That might be the cause

**Comment by arschles** [comment]
@tomkerkhove I don't have permissions to look at this. I suspect that the container images need to be made public (https://docs.github.com/en/packages/guides/configuring-access-control-and-visibility-for-container-images#configuring-visibility-of-container-images-for-an-organization). Can you take a look?

**Comment by khaosdoctor** [comment]
I'm getting a different error, but same stuff

![image](https://user-images.githubusercontent.com/3200560/107091373-7056bd00-67e0-11eb-9427-a8b251ad3dcf.png)

**Comment by tomkerkhove** [comment]
The error is correct as they are published as private images by default. Feel free to assign to me and I'll make them public asap.

**Comment by tomkerkhove** [comment]
Please try again. They are now also linked to this repo and available here https://github.com/orgs/kedacore/packages?repo_name=http-add-on

**Comment by khaosdoctor** [comment]
It seems to be working now. I can download the image :)

**Comment by khaosdoctor** [comment]
I think #45 and #41 can be merged now

**Comment by arschles** [comment]
@tomkerkhove thank you!

@khaosdoctor I'm going to merge #45 and cut a release today, then I'll move on to #41 and beyond

**Comment by arschles** [comment]
Closing as this works now. Thanks everyone

**Comment by shalev123d** [comment]
Hey, we're experiencing this issue as well - 
docker pull ghcr.io/kedacore/keda-metrics-apiserver:2.7.1 - 
```
error pulling image configuration: unauthorized: unauthenticated: User cannot be authenticated with the token provided.
```
