### ISSUE TITLE
keda-add-ons-http-external-scaler pod won't work after installation

### ISSUE THREAD

**Issue by JieDing** [kedacore/http-add-on#481]
### Report

I try to install http-add-on via helm, but keda-add-ons-http-external-scaler won't work after installation.

I use the following command to install latest version of http-add-on:

```shell
helm install http-add-on kedacore/keda-add-ons-http --create-namespace --namespace keda --set images.tag=canary
```

I copied the command from the [install.md](https://github.com/kedacore/http-add-on/blob/main/docs/install.md) .

### Expected Behavior

```
$ kubectl get deploy -n keda
NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
keda-add-ons-http-controller-manager   1/1     1            1           116s
keda-add-ons-http-external-scaler      1/1     1            1           116s
keda-add-ons-http-interceptor          1/1     1            1           116s
```

### Actual Behavior

```
$ kubectl get deploy -n keda
NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
keda-add-ons-http-controller-manager   1/1     1            1           116s
keda-add-ons-http-external-scaler      0/1     1            0           116s
keda-add-ons-http-interceptor          1/1     1            1           116s
```

### Steps to Reproduce the Problem

1. helm install http-add-on kedacore/keda-add-ons-http --create-namespace --namespace keda --set images.tag=canary
2. kubectl get po -n keda
3. kubectl logs -f keda-add-ons-http-external-scaler-7f4746786c-cn2vc -n keda

### Logs from KEDA HTTP operator

Here are logs from keda-add-ons-http-external-scaler pod:

```
$ kubectl logs -f keda-add-ons-http-external-scaler-7f4746786c-cn2vc -n keda
panic: required key KEDA_HTTP_SCALER_TARGET_ADMIN_DEPLOYMENT missing value

goroutine 1 [running]:
github.com/kelseyhightower/envconfig.MustProcess(...)
	/go/pkg/mod/github.com/kelseyhightower/envconfig@v1.4.0/envconfig.go:233
main.mustParseConfig()
	/go/src/github.com/kedacore/http-add-on/scaler/config.go:45 +0x5f
main.main()
	/go/src/github.com/kedacore/http-add-on/scaler/main.go:37 +0x112
```

### What version of the KEDA HTTP Add-on are you running?

0.3.0

### Kubernetes Version

Other

### Platform

Other

**Comment by JerryWang20** [comment]
i met the same issue, what's the solution for it?
