### ISSUE TITLE
Provide support for autoscaling based on HTTP response time

### ISSUE THREAD

**Issue by KowsikRS** [kedacore/http-add-on#489]
Keda autoscaling based on HTTP response time. If there is a delay in response time , KEDA should auto-scale the pods

**Comment by nrukavkov** [comment]
I think it could be worst for k8s cluster because we do not know the reason why response time is growing. It could be critical cpu usage and then autoscaling based on HTTP response time could make it worse

**Comment by kowsik1994** [comment]
If CPU usage is critical you can add CPU trigger for autoscaling

**Comment by vitobotta** [comment]
I would like scaling based on response time too or something like that. Besides that, how can I combine an HTTPScaledObject with CPU metrics for scaling? Thanks

**Comment by tomkerkhove** [comment]
@arschles Does our current spec allow scaling with other built-in KEDA scalers? I don't think so? If it does not, I'll open an issue

**Comment by JorTurFer** [comment]
> did anyone figure out how to use this + the CPU scaler?

Currently, it's not supported because the HTTPScaledObject doesn't support any other source than the HTTP metrics.
[This PR was promising](https://github.com/kedacore/http-add-on/pull/795), but it looks stale

**Comment by devopsdynamo** [comment]
I've created new PR which will allow for HTTP scaler to be used alongside other scalers.
https://github.com/kedacore/http-add-on/pull/929

**Comment by JorTurFer** [comment]
This seems that has been stale for a long time. I close this as thanks to https://github.com/kedacore/http-add-on/pull/929 there is a workaround now. If someone thinks that this is still something required, let's open another issue and discuss the best design considering current features
