### ISSUE TITLE
cut headers

### ISSUE THREAD

**Issue by nrukavkov** [kedacore/http-add-on#535]
### Report

I installed grafana in k8s using custom helm chart (with ingress and external url) - and everything works fine. Then I added http keda addon and now I'm getting an error: origin not allowed. I suppose it is happened because http addon erase headers.

### Expected Behavior

Do not erase headers.

### Steps to Reproduce the Problem

Install grafana to k8s and integrate keda addon to it.

**Comment by nrukavkov** [comment]
Host Header is not correct
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/54890287/198249386-d5e5da92-9bd9-4f5b-b4f2-ebb2070f5c46.png">

**Comment by yxxhero** [comment]
@tomkerkhove assign to me?

**Comment by tomkerkhove** [comment]
Certainly, thanks!

**Comment by bbrala** [comment]
This shouldn't have been close it seems

**Comment by tomkerkhove** [comment]
Nobody raised it again so our process cleans up the backlog. If you are still seeing it, I'm happy to re-open it then.

**Comment by bbrala** [comment]
fair enough

**Comment by tomkerkhove** [comment]
Are you still seeing it?

**Comment by bbrala** [comment]
I'm not sure, i'm not getting this scaling working on my cluster anyhow so I'm not even getting this far. I just keep an eye out on this repo since i really want this for my acceptance cluster. This issue just seemed weird.
