### ISSUE TITLE
Upgrading the helm installation breaks all HTTPScaledObjects

### ISSUE THREAD

**Issue by strongpauly** [kedacore/http-add-on#549]
### Report

If we want to upgrade using the helm chart, it appears to break all existing deployments.  The deployed HTTPScaledObjects should be respected.

It's doubly bad because re-applying the existing configuration doesn't work, because k8s thinks nothing has changed.  The objects need to be deleted, then re-added.

### Expected Behavior

All current `HTTPScaledObjects` should be respected and applied.

### Actual Behavior

`HTTPScaledObjects`  still exist in the system, but must be deleted and re-applied for their hosts to be accessible from the `http-interceptor-proxy`

### Steps to Reproduce the Problem

1. Install Keda:
```
helm repo add kedacore https://kedacore.github.io/charts
helm repo update
export NAMESPACE=keda
helm install keda kedacore/keda -n ${NAMESPACE}
```

2. Install the HTTP addon
```
helm install http-add-on kedacore/keda-add-ons-http  -n ${NAMESPACE}
```

3. Configure some HTTPScaledObjects in that namespace.

4. Upgrade the helm chart (perhaps with new values)
```
helm upgrade -n ${NAMESPACE} http-add-on kedacore/keda-add-ons-http
```

### Logs from KEDA HTTP operator

```
{"level":"error","ts":1669896742.1477597,"logger":"GetMetricSpec","caller":"scaler/handlers.go:130","msg":"error getting target for host","host":"backend-svc","error":"Target not found","stacktrace":"main.(*impl).GetMetricSpec\n\t/go/src/github.com/kedacore/http-add-on/scaler/handlers.go:130\ngithub.com/kedacore/http-add-on/proto._ExternalScaler_GetMetricSpec_Handler\n\t/go/src/github.com/kedacore/http-add-on/proto/scaler_grpc.pb.go:178\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1282\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1616\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:921"}
```

### What version of the KEDA HTTP Add-on are you running?

0.3.0

### Kubernetes Version

1.21

### Platform

Amazon Web Services

### Anything else?

Running K8s on AWS EKS

**Comment by tomkerkhove** [comment]
Odd. Is it because of an outdated CRD spec or so?

**Comment by strongpauly** [comment]
It's possible there were previous attempts at moving the addon (and Keda core) to different namespaces.  
I also came across this issue when attempting to remove everything: https://github.com/kubernetes/kubernetes/issues/60538#issuecomment-369099998

**Comment by tomkerkhove** [comment]
Hm odd and I'm afraid it might be hard to investigate in that case. Can you keep an eye out if this happens again please?

**Comment by strongpauly** [comment]
It literally happened every time I reapplied the addon, which was 2 or 3 times. This was a deal breaker for me so have since implemented alternative deployment options.

**Comment by tomkerkhove** [comment]
That's easy to reproduce then and we'll need to fix that; thanks.

**Comment by trilitheus** [comment]
I've just hit the same issue - I needed to redeploy to change a header timeout - no version upgrade:

    $ helm history http-add-on
    ....
    4       	Wed Feb  1 12:09:49 2023	superseded	keda-add-ons-http-0.4.1	0.4.0      	Upgrade complete
    5       	Thu Feb 16 15:49:23 2023	deployed  	keda-add-ons-http-0.4.1	0.4.0      	Upgrade complete

all httpscaledobjects were still in place but the external-scaler no longer recognised them - deleting the keda-add-ons-http-external-scaler pod caused it to 're-read' the httpscaledobjects and everything started working again.
