### ISSUE TITLE
Improve e2e test

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/http-add-on#582]
Currently, we are executing a single bash script for e2e tests which does this:
1. install KEDA
2. deploy the add-on
3. deploy a workload with http-scaledobject
4. check resources
5. wait till workload is scaled to 0
6. add traffic
7. wait till workload is scaled to 1
8. clear resources

To improve the test suite and to add the option to increase covered cases, we should adopt an approach like [KEDA does in the main repo](https://github.com/kedacore/keda/tree/main/tests). 

This will give us the option to easily add new test cases like testing Prometheus metrics

## Action Items

- [x] Align with KEDA Core's e2e testing approach https://github.com/kedacore/http-add-on/pull/686
- [x] Increase test coverage

### New test cases to add

- [x] Prometheus metrics
- [x] More than 1 HttpScaledobject
- [x] The scaling phase (currently, we are testing only the activation phase)
- [x] Test with a single/multiple instances.
- [x] Any bug we can reproduce, should be added as test to reduce the regressions

**Comment by tomkerkhove** [comment]
So what do do you have in mind to improve the e2e experience other than aligning with KEDA core?

**Comment by JorTurFer** [comment]
> So what do you have in mind to improve the e2e experience other than aligning with KEDA core?

That is already a good improvement :)

I think we should add more test cases like:
- Prometheus metrics
- More than 1 HttpScaledobject
- The scaling phase (currently, we are testing only the activation phase)
- Test with a single/multiple instances.
- Any bug we can reproduce, should be added as test to reduce the regressions

**Comment by tomkerkhove** [comment]
Let's list them in the description as well then!

**Comment by tomkerkhove** [comment]
Done
