### ISSUE TITLE
Add branch protection rule

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#63]
Add a branch protection rule for the `main` branch to ensure:

- the branch is up to date before merging
- contributors can't push directly to the `main` branch
- status checks all pass before merge
- PR reviews should be done before merge

### Use-Case

The above list is important for the health of all pull requests, because it ensures that the code in them is tested against the up-to-date main branch (to which it's going to be merged) and otherwise of a good quality

### Specification

See attached screenshot. The checked boxes represent almost everything in the list herein.

<img width="1680" alt="Screen Shot 2021-02-11 at 3 03 58 PM" src="https://user-images.githubusercontent.com/70865/107709690-79c9a480-6c7a-11eb-8018-a6933b9ea082.png">

@tomkerkhove can you do this?

**Comment by tomkerkhove** [comment]
Done!
