### ISSUE TITLE
Upgrade controller-runtime dependency

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#64]
We're currently on [v0.5.0](https://github.com/kedacore/http-add-on/blob/main/go.mod#L18) but the latest version is [v0.8.2](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.8.2).

**Comment by khaosdoctor** [comment]
I think this has been updated already here: https://github.com/kedacore/http-add-on/commit/ebef98e5147b78f83b91b9337c76782f48ee926f#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6

**Comment by arschles** [comment]
Right you are. Thanks @khaosdoctor
