### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by jocelynthode** [kedacore/http-add-on#697]
Hey,

there were many changes added since the last release notably a fix for `scaleDownPeriod` to work and multi hosts configuration.

Is there any plan for a release soonish?

**Comment by tomkerkhove** [comment]
We're planning to do one after https://github.com/kedacore/http-add-on/pull/669 is done by @t0rr3sp3dr0.

Anything else you want @JorTurFer?

**Comment by JorTurFer** [comment]
Maybe this one is interesting too: https://github.com/kedacore/http-add-on/pull/677

**Comment by t0rr3sp3dr0** [comment]
Can you close this @JorTurFer?
