### ISSUE TITLE
Release: v0.5.0

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/http-add-on#715]
This issue template is used to track the rollout of a new KEDA HTTP add-on version.

For the full release process, we recommend reading [this document]([https://github.com/kedacore/keda/blob/main/RELEASE-PROCESS.md](https://github.com/kedacore/http-add-on/blob/main/RELEASE-PROCESS.md)).

## Required items

- [x] List items that are still open, but required for this release

# Timeline

We aim to release this release in the week of June 19th.

## Progress

- [x] Add the new version to GitHub Bug report template
- [x] Create KEDA release
- [x] Prepare & ship Helm chart
- [x] Publish on Artifact Hub ([repo](https://github.com/kedacore/external-scalers))
- [ ] Provide update in Slack
- [ ] Tweet about new release

**Comment by tomkerkhove** [comment]
https://github.com/kedacore/charts/releases/tag/keda-add-ons-http-v0.5.0

**Comment by jocelynthode** [comment]
Hey, the new chart is not available through https://kedacore.github.io/charts. I also don't see it on artifacthub. (Checked here: https://artifacthub.io/packages/helm/kedacore/keda-add-ons-http)

Did something fail during the helm chart ship?

**Comment by JorTurFer** [comment]
> Did something fail during the helm chart ship?

Thanks for the heads-up! Yes, the deployment pipeline failed. I have re-executed the workflow and it has passed. You can use it now and you can see it with `helm repo update`. IDK how artifacthub works but if it's based on the repo feed, I guess that it will be updated soon

**Comment by jocelynthode** [comment]
@JorTurFer I noticed 2 issues while trying the upgrade in the helm chart which breaks deployment, which I've reported there:

- https://github.com/kedacore/charts/issues/472
- https://github.com/kedacore/charts/issues/473

I also noticed that the `ConfigMap` for the routing table is still there even though I think we don't need it anymore.

After manually fixing those I was still getting errors and had to stop there and rollback. I'll try to investigate in the following days and see if I can provide a better bug report or if it's something on my end.

**Comment by JorTurFer** [comment]
Thanks for reporting the issues. I'll check them later on and hopefully the fix will be today or tomorrow

**Comment by JorTurFer** [comment]
This PR should fix both issues, thanks for reporting them: https://github.com/kedacore/charts/pull/474

**Comment by jocelynthode** [comment]
Thanks for the PR. I've also noted both these issues directly on the add-on related to the 0.5.0:
- https://github.com/kedacore/http-add-on/issues/717
- https://github.com/kedacore/http-add-on/issues/718

The first one might be breaking for some users I know I got caught by it trying to deploy the new version on our stage cluster.

**Comment by JorTurFer** [comment]
Thanks for reporting them too ❤️ 
Are you willing to contribute with any of them by chance? don't worry if no, we will try to fix them in any case

**Comment by jocelynthode** [comment]
I'll have to see if I can free some time at work to take on an issue next week.

I could try and tackle the label one. However I'll need to brush up on the routing table as I have not looked at all into the new implementation code.

-------- Message d'origine --------

**Comment by t0rr3sp3dr0** [comment]
@jocelynthode, the issues should be fixed and the following PRs get merged:
- https://github.com/kedacore/charts/pull/487
- https://github.com/kedacore/http-add-on/pull/720
- https://github.com/kedacore/http-add-on/pull/721

**Comment by t0rr3sp3dr0** [comment]
@JorTurFer @tomkerkhove, I think we should release a new version as soon as kedacore/charts#487 and #720 get merged. The interceptor scaling is completely broken on v0.5.0.

**Comment by jocelynthode** [comment]
Thanks for the very quick fixes! As soon as a new version with all 3 fixes is released I'll try to upgrade and test it again on real workloads!

-------- Message d'origine --------

**Comment by tomkerkhove** [comment]
> @JorTurFer @tomkerkhove, I think we should release a new version as soon as [kedacore/charts#487](https://github.com/kedacore/charts/pull/487) and #720 get merged. The interceptor scaling is completely broken on v0.5.0.

Can you please check why our testing did not fail?

**Comment by JorTurFer** [comment]
> Can you please check why our testing did not fail?

It's because the interceptor scaling itself isn't tested during e2e tests

**Comment by t0rr3sp3dr0** [comment]
And the manifests on this repository did not indicate we supported this. This was something that was only configured on the Helm Chart. So when I reimplemented the routing table, this feature was erroneously removed.

**Comment by tomkerkhove** [comment]
> > Can you please check why our testing did not fail?
> 
> It's because the interceptor scaling itself isn't tested during e2e tests

Which begs the question - Why? Can we add this?

**Comment by JorTurFer** [comment]
This process is similar as in core, we need to manually port the changes in manifests from code repo to helm repo and it could have human fails

**Comment by jocelynthode** [comment]
Hey, are we still missing a fix or could we release a 0.5.x hotfix version as the current version (0.5.0) does not have the fixes and I'd prefer not having to use a specific tag from a commit.

**Comment by tomkerkhove** [comment]
We're waiting for https://github.com/kedacore/http-add-on/pull/727 & https://github.com/kedacore/http-add-on/pull/700

**Comment by jocelynthode** [comment]
Hey @tomkerkhove: I see that #700 is still open. Is there something I could do to help move it forward so that we can cut a hotfix? I'd really like to upgrade to 0.5 as there are a lot of cool things in this release :smiley:

**Comment by JorTurFer** [comment]
Hi @jocelynthode 
I guess that until the end of August we won't cut a release as we are during summer break: https://github.com/kedacore/keda/issues/4773

In any case, I think that we can close this issue and aim to a version 0.5.1 or 0.6.0

**Comment by tomkerkhove** [comment]
I'm fine with 0.5.1 or 0.6.0.

Closing
