### ISSUE TITLE
Document HTTPScaledObject in docs

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/http-add-on#728]
### Proposal

Currently, we don't have documented anywhere the HTTPScaledObject spec. This makes it complex to use in other case as the examples. [Like we do in core](https://keda.sh/docs/2.11/concepts/scaling-deployments/#scaledobject-spec), we should document HTTPScaledObject spec as part of the docs in the repo.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by JorTurFer** [comment]
@tomkerkhove , do you know if there is any way to version current docs? HTTPScaledObject changes during versions, and if the docs can have versions it'd be nice, and if it's not possible, we should document all the versions in different files or sections (IMO)

**Comment by B1F030** [comment]
Hi! I'm glad to help, can I create a PR to work on this?

**Comment by JorTurFer** [comment]
This is already documented -> https://github.com/kedacore/http-add-on/tree/main/docs/ref
