### ISSUE TITLE
Add documentation for the HTTPScaledObject schema

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#74]
We only have the code and example YAML at the moment. We should document this much better in the repo

**Comment by tomkerkhove** [comment]
Happy to review it along with a sample!

**Comment by khaosdoctor** [comment]
@tomkerkhove I can create an initial version and upload it here so we have all the docs ready, then we can change it when we update

**Comment by tomkerkhove** [comment]
That's fine for me! But for me it's ok if it's in the repo already and we change it there as well.

**Comment by arschles** [comment]
I added a reference for it in https://github.com/kedacore/http-add-on/pull/78 - sorry I forgot to tab this issue in there!
