### ISSUE TITLE
"Host" header not transmited normally to the pod

### ISSUE THREAD

**Issue by benaly97** [kedacore/http-add-on#764]
### Report

I have Kubernetes cluster with an nginx ingress controller and use keda-http-add-on.
When I use keda-add-ons-http-interceptor-proxy as ingress backend, the "Host" header get in my application (the pod) is not the the original "Host" header. 

### Expected Behavior

Is a way to tell keda-http-add-on to set the Host header transmitted by the ingress as Host header?

### Actual Behavior

I work with a librairie that build an url based on "Host" header.

If i have the app URL "https://www.myappurl.com" to access my application, without using  keda-add-ons-http-interceptor-proxy, the librairie can build normally the URL "https://www.myappurl.com" in my application. 

But when using  keda-add-ons-http-interceptor-proxy as ingress backend,  the librairie build an URL like https://my_app_service_name.namespace:my_app_service_port.

### Steps to Reproduce the Problem

1. Use directly my app service as backend on the ingress . The "Host" header get in my application is my host url like www.myappurl.com

2. Use keda-add-ons-http-interceptor-proxy as service backend on the ingress. The "Host" header get in my application seem like my_app_service_name.namespace:my_app_service_port

### HTTP Add-on Version

0.5.0

### Kubernetes Version

Other

### Platform

Other

### Anything else?

Kubernetes version : 1.27
Helm chart : version: 0.5.2

**Comment by jocelynthode** [comment]
It's already fixed: https://github.com/kedacore/http-add-on/pull/746 however you'll have to wait for a release to be cut.

**Comment by benaly97** [comment]
Thank's for your response. Wait for it.

**Comment by kjfly** [comment]
Hi, we have the same issue and it is preventing us from using the http-add-on. Is it possible to get the release soon? Thanks.

**Comment by JorTurFer** [comment]
We have released v0.6.0 this week :)
