### ISSUE TITLE
How to combine this with other Keda triggers

### ISSUE THREAD

**Issue by kjfly** [kedacore/http-add-on#816]
### Discussed in https://github.com/kedacore/http-add-on/discussions/455

<div type='discussions-op-text'>

<sup>Originally posted by **tidunguyen** May 20, 2022</sup>
I want to use multiple triggers for my deployment. How can I combine this tool with other Keda triggers so that my app can be activated whenever any trigger run.
I tried to edit the auto-created ScaledObject created by this controller and managed to trigger the app. However, it does not work as expected in several cases. For example:
- CooldownPeriod is always 300s no matter how much I set
- App does not get scaled down occasionally
- Sometimes, app is stucked in a scaled up then terminated instantly loop

What is the idiomatic way to do this or this use case is not yet supported and is supposed to give undefined behaviors?</div>

**Comment by JorTurFer** [comment]
Hi!
Currently it's not possible but this [on-going PR](https://github.com/kedacore/http-add-on/pull/795) allows to not generating the ScaledObject from HTTPScaledObject, so you will have the option to treat the HTTP metrics source as an external source on your own ScaledObject (and this unlocks all the options already supported but the ScaledObjects)
