### ISSUE TITLE
Support auto-scaling an existed deployment after a cooldown period

### ISSUE THREAD

**Issue by thincal** [kedacore/http-add-on#887]
### Proposal

It seems that only the scaleTarget be scaled up by the KEDA could be applied with the cooldown period, but I have two cases might be violate this design:

case 1: I want to create a deployment with initial replica 1 and a scale object with min replica 0, but the result is when the replica pod created then it would be scaled down immediately controlled by the KEDA.

case 2: I have some deployments already running for a while, but I want to create a scale object on the fly to manage it for the scaling to zero ability. as same as case 1, after the scale object created the target deployment would be scaled to zero.

After dig into the KEDA code, it says clearly that:

// LastActiveTime can be nil if the ScaleTarget was scaled outside of KEDA.
// In this case we will ignore the cooldown period and scale it down

so, the scale to zero is applied immediately but it's not really wait for a cooldown period just after scale object created.

### Is this a feature you are interested in implementing yourself?

No

**Comment by JorTurFer** [comment]
Hello,
Thanks for reporting! This issue can't be managed in the Add-on side as it's KEDA who is doing that. There is an issue in KEDA side: https://github.com/kedacore/keda/issues/5008. 
Let's move the conversation to there. Your use case makes sense totally but nothing can be done here
