### ISSUE TITLE
Improve the status field of HTTPScaledObjects

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#9]
Currently, the `Status` field is not updated

## Expected Behavior

- The `status` field needs to be updated properly after an `HTTPScaledObject` gets created
- The `status` field should have a `conditions` list, similar to the one in `ScaledObject`s. That way, there is an auditable log of mutations of the `HTTPScaledObject`

## Actual Behavior

The status field remains blank

## Steps to Reproduce the Problem

  1. `kubectl create -f examples/httpscaledobject.yaml`
  2. Observe application components like `Service` and `Deployment` get created
  3. `kubectl get -n kedahttp xkcd -o yaml`
  4. Observe that there is no `status` field

## Specifications

N/A

  - **KEDA Version:** *Please elaborate*
  - **Platform & Version:** *Please elaborate*
  - **Kubernetes Version:** *Please elaborate*
  - **Scaler(s):** *Please elaborate*

**Comment by arschles** [comment]
cc/ @khaosdoctor

**Comment by khaosdoctor** [comment]
On it

**Comment by khaosdoctor** [comment]
@arschles can you add me as assignee?
