### ISSUE TITLE
The current walkthrough seems stale

### ISSUE THREAD

**Issue by arav-agarwal2** [kedacore/http-add-on#908]
### Report

I have an AKS cluster that I was trying to get this add-on working on, and I've managed to:
1. Install the add on successfuly.
2. Install the xkcd release.
3. Try to install the scaleobject for 0.7.0 ( note: the xkcd chart as-is tries to install a scaledobject, which is clearly wrong )
However, when I forward the port ( which the port is wrong - the interceptor only exposes port 8080 not 80 ), I still can't access the app. 

### Expected Behavior

I was expecting the app to show something - anything really - so I can confirm that this project is working as expected on azure aks.

### Actual Behavior

I can't seem to find any route that displays anything to know if this works.

### Steps to Reproduce the Problem

1. Create an azure AKS cluster.
2. Follow the given steps to install keda and the http-add-on.
3. See error?

### Logs from KEDA HTTP operator

```
example
```

### HTTP Add-on Version

0.7.0

### Kubernetes Version

1.27

### Platform

Microsoft Azure

**Comment by JorTurFer** [comment]
Hello,
Where are you taking xkcd chart from? I've checked the chart within examples folder and I think that it works (maybe there is something broken, but I checked it 2 months ago and I fixed the issues). 
https://github.com/kedacore/http-add-on/tree/main/examples/xkcd

**Comment by JorTurFer** [comment]
I've also checked the walkthrough page: https://github.com/kedacore/http-add-on/blob/main/docs/walkthrough.md
I've seen some minor mismatches (which I'll solve later on), but they are minor things like minor changes in service name, but almost all is correct, and definitively I don't see the differences you have reported :( 

Maybe I'm missing something (which is probably), could you share the link that you have checked? (probably there is something not updated that we have to fix)

**Comment by JorTurFer** [comment]
I'm checking step by step and it looks that some steps are broken since the last review 😢

**Comment by JorTurFer** [comment]
Could you try using [this page](https://github.com/JorTurFer/http-add-on/blob/fix-walkthrough/docs/walkthrough.md)? (I have reviewed it but maybe there is still something wrong)
