### ISSUE TITLE
Interceptor Proxy - OTEL Instrumentation

### ISSUE THREAD

**Issue by zorocloud** [kedacore/http-add-on#910]
### Proposal

Currently the interceptor proxy does not emit any metrics or traces which makes it difficult to understand how the service is performing. It should use OTEL instrumentation to provide observability, making it easier to monitor key performance attributes of the service in a real world setting.

### Use-Case

Running the interceptor proxy in a production setting where having insight into the performance of your platform services is key.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by zorocloud** [comment]
Yes I'm happy to do that. I actually know someone who is interested in contributing the trace portion of this, is it possible for both of us to take the issue and split it?

**Comment by JorTurFer** [comment]
> Yes I'm happy to do that. I actually know someone who is interested in contributing the trace portion of this, is it possible for both of us to take the issue and split it?

I think so. You can work in a single fork together if both parts are required for working, or just in to PRs if they can work independently, in that case, the second PR will just rebase the first one and validates that it works

**Comment by zorocloud** [comment]
> just in to PRs if they can work independently, in that case, the second PR will just rebase the first one and validates that it works

Sweet, will go with this approach :)

**Comment by zorocloud** [comment]
@JorTurFer I have raised an initial PR for metrics support. I don't seem to be able to link it to this issue though so have linked it below. Let me know your thoughts :) 

https://github.com/kedacore/http-add-on/pull/927
