### ISSUE TITLE
Add integration with Application Gateway for Containers for HTTP ingress

### ISSUE THREAD

**Issue by tedvanderveen** [kedacore/http-add-on#933]
### Proposal

Integrate KEDA-HTTP with Azure Application Gateway for containers. AGC aligns with the k8s Gateway API 1.0.0 spec (released a couple of months ago) and provides loadbalancer/firewall ingress (L7 loadbalancer) for AKS. 
https://learn.microsoft.com/en-us/azure/application-gateway/for-containers/overview#how-does-it-work
![image](https://github.com/kedacore/http-add-on/assets/1763519/fa9fe6fc-d2f3-4f4a-b849-29ab5994e6a2)

### Use-Case

Having one integrated solution for handling incoming HTTP traffic for AKS and handle scaling (to zero) of web apps on AKS.

### Is this a feature you are interested in implementing yourself?

No

**Comment by tomkerkhove** [comment]
Mind elaborating on how you see this in action? Are you asking to make it part of AGC?

**Comment by tedvanderveen** [comment]
@tomkerkhove I'm sorry for not getting back to you sooner. What I was referring to, is to use AGC telemetry data to scale HTTP workloads in the cluster. When reading [this](https://github.com/kedacore/http-add-on/blob/81f7469ad1f9094ab43057d249ab3eb857b754a0/README.md?plain=1#L33) section of the project main Readme, I was thinking that AGC could be well equiped to supply needed metrics data about ingress HTTP events.

**Comment by tedvanderveen** [comment]
@tomkerkhove I now noticed how you raised the same subject [here](https://github.com/kubernetes-sigs/gateway-api/issues/554)
