### ISSUE TITLE
Http-External-Scaler: Unauthorized error when connecting to k8s control plane

### ISSUE THREAD

**Issue by Destiro** [kedacore/http-add-on#974]
### Report

Hi Team! We are unsure if this is an issue on our side, would like to see if you have any guidance on this issue.

### Problem
We have experienced twice (once on 2024-02-07 and another on 2024-03-21) an issue where our http-add-ons failed due to refused connections between http-external-scaler and http-interceptor. When this issue occurs, we are able to resolve it by restarting the http-external-scaler pod, but as this has occurred twice seems like it may be an ongoing issue.

Our KEDA setup has been working correctly without issues (we have been using since June 2023). The error messages are primarily 401's (Unauthorized) which made us suspect that a certificate has been expired, however we cannot find any expired certificate. Due to the lack of connection between the scaler and the interceptor we were experiencing scaling of our deployments to 0.

### What we have tested:
* ca.cert for keda-http-external-scaler-token is valid until 2029
* ca.cert for keda-add-ons-http-token is valid until 2029
* ca.cert for keda-http-interceptor-token is valid until 2029
* ca.cert for keda-operator-token is valid until 2029
* ca.cert for kedaorg-certs is valid until 2023
* Apiservice certs for KEDA metrics server are valid

### Expected Behavior

Http-External-Scaler continues connection with Http-Interceptor.

### Actual Behavior

Http-External-Scaler occasionally gets 401 (Unauthorized) errors when sending requests to Http-Interceptor.

### Steps to Reproduce the Problem

1. Install KEDA and Http-add-ons
2. Wait

### Logs from KEDA HTTP operator

**Logs from Interceptor:**
`{"level":"error","ts":1711005503.465923,"caller":"interceptor/proxy_handlers.go:73","msg":"wait function failed, not forwarding request","error":"context marked done while waiting for deployment deployment-name to reach > 0 replicas: context canceled","stacktrace":"main.newForwardingHandler.func1\n\[tgithub.com/kedacore/http-add-on/interceptor/proxy_handlers.go:73](http://tgithub.com/kedacore/http-add-on/interceptor/proxy_handlers.go:73)\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2122\[ngithub.com/kedacore/http-add-on/interceptor/middleware.(*Counting).ServeHTTP](http://ngithub.com/kedacore/http-add-on/interceptor/middleware.(*Counting).ServeHTTP)\n\[tgithub.com/kedacore/http-add-on/interceptor/middleware/counting.go:34](http://tgithub.com/kedacore/http-add-on/interceptor/middleware/counting.go:34)\[ngithub.com/kedacore/http-add-on/interceptor/middleware.(*Routing).ServeHTTP](http://ngithub.com/kedacore/http-add-on/interceptor/middleware.(*Routing).ServeHTTP)\n\[tgithub.com/kedacore/http-add-on/interceptor/middleware/routing.go:61](http://tgithub.com/kedacore/http-add-on/interceptor/middleware/routing.go:61)\[ngithub.com/kedacore/http-add-on/interceptor/middleware.(*Logging).ServeHTTP](http://ngithub.com/kedacore/http-add-on/interceptor/middleware.(*Logging).ServeHTTP)\n\[tgithub.com/kedacore/http-add-on/interceptor/middleware/logging.go:42](http://tgithub.com/kedacore/http-add-on/interceptor/middleware/logging.go:42)\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:2936\nnet/http.(*conn).serve\n\tnet/http/server.go:1995"}
{"level":"info","ts":1711005503.4660518,"logger":"LoggingMiddleware","caller":"middleware/logging.go:73","msg":"10.126.99.197:58304 - - [21/Mar/2024:07:17:23 +0000] \"GET / HTTP/1.1\" 502 130 \"\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36\""}`

**Logs from KEDA Metrics API server:**
`I0321 02:28:36.390473    1 trace.go:236] Trace[401953074]: "List" accept:application/vnd.kubernetes.protobuf, */*,audit-id:aa166140-c7df-43f5-a050-7197e86319d3,client:172.16.46.77,protocol:HTTP/2.0,resource:s0-http-atlantis_002fatlantis-ghec-paas-sql-httpscaledobject,scope:namespace,url:/apis/external.metrics.k8s.io/v1beta1/namespaces/atlantis/s0-http-atlantis_002fatlantis-ghec-paas-sql-httpscaledobject,user-agent:kube-controller-manager/v1.25.16 (linux/amd64) kubernetes/ea12af9/system:serviceaccount:kube-system:horizontal-pod-autoscaler,verb:LIST (21-Mar-2024 02:28:35.887) (total time: 502ms):`

**Logs from KEDA Operator:**
`2024-02-07T22:28:34Z	ERROR	external_scaler	error	{"type": "ScaledObject", "namespace": "keda", "name": "keda-add-ons-http-interceptor", "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 172.20.45.234:9090: connect: connection refused\""}
github.com/kedacore/keda/v2/pkg/scalers.(*externalScaler).GetMetricSpecForScaling
	/workspace/pkg/scalers/external_scaler.go:172
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).GetMetricSpecForScalingForScaler
	/workspace/pkg/scaling/cache/scalers_cache.go:104
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState
	/workspace/pkg/scaling/scale_handler.go:552
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:236
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:175
2024-02-07T22:28:34Z	ERROR	external_scaler	error	{"type": "ScaledObject", "namespace": "keda", "name": "keda-add-ons-http-interceptor", "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 172.20.45.234:9090: connect: connection refused\""}
github.com/kedacore/keda/v2/pkg/scalers.(*externalScaler).GetMetricSpecForScaling
	/workspace/pkg/scalers/external_scaler.go:172
github.com/kedacore/keda/v2/pkg/scaling/cache.(*ScalersCache).GetMetricSpecForScalingForScaler
	/workspace/pkg/scaling/cache/scalers_cache.go:113
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScaledObjectState
	/workspace/pkg/scaling/scale_handler.go:552
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).checkScalers
	/workspace/pkg/scaling/scale_handler.go:236
github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).startScaleLoop
	/workspace/pkg/scaling/scale_handler.go:175`

172.20.45.234:9090 is keda-add-ons-http-external-scaler

**Logs from External Scaler:**
`{"log":{"caller":"scaler/main.go:118","error":"error getting request counts: pkg.k8s.EndpointsForService: Unauthorized","level":"error","msg":"queue pinger failed","stacktrace":"main.main.func3\n\tgithub.com/kedacore/http-add-on/scaler/main.go:118\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.3.0/errgroup/errgroup.go:75","ts":1706859453.397548},"stream":"stderr","timestamp":1706859453398}`

### HTTP Add-on Version

0.5.0

### Kubernetes Version

< 1.27

### Platform

Amazon Web Services

**Comment by JorTurFer** [comment]
Could you confirm that you are using version `0.5.0`? There have been several performance improvements and some bug fixes in latest versions , and we will cut a release for v0.8.0 during this week or the next week (which includes several new features like aggregation windows).
If you are using 0.5.0 I'd suggest upgrading the add-on to 0.8.0 once it's available

**Comment by Destiro** [comment]
Yup we are currently on `0.5.0` Ive had a check through some of the closed issues and believe that upgrading to `0.7.0`/`0.8.0` is the best course of action.

Our issue looks related to this fix: https://github.com/kedacore/http-add-on/commit/7908755121f1a3d5e1858f21d0204a0e993492f3 that is included in the `0.7.0` release.

Thanks for the prompt response! Hope you have a great day, will close the issue now :D
