### ISSUE TITLE
Scalar crashloops with there isn't any valid interceptor endpoint message

### ISSUE THREAD

**Issue by shreya0910** [kedacore/http-add-on#978]
### Report

Deployed Keda Http add on v0.7.0, other components are coming up but scalar ris crashlooping with below message
{"level":"error","ts":1713393132.759042,"logger":"scaler.queuePinger.start","caller":"scaler/queue_pinger.go:100","msg":"context marked done. stopping queuePinger loop","erro │
│ r":"context canceled","stacktrace":"main.(*queuePinger).start\n\tgithub.com/kedacore/http-add-on/scaler/queue_pinger.go:100\nmain.main.func3\n\tgithub.com/kedacore/http-add-o │
│ n/scaler/main.go:110\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.6.0/errgroup/errgroup.go:78"}  

### Expected Behavior

Scalar should get deployed and pods should come up

### Actual Behavior

{"level":"error","ts":1713393132.759042,"logger":"scaler.queuePinger.start","caller":"scaler/queue_pinger.go:100","msg":"context marked done. stopping queuePinger loop","erro │
│ r":"context canceled","stacktrace":"main.(*queuePinger).start\n\tgithub.com/kedacore/http-add-on/scaler/queue_pinger.go:100\nmain.main.func3\n\tgithub.com/kedacore/http-add-o │
│ n/scaler/main.go:110\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.6.0/errgroup/errgroup.go:78"}  

### Steps to Reproduce the Problem

1. Install Keda http add on 
kedacore/keda-add-ons-http                      0.7.0           0.7.0           

### Logs from KEDA HTTP operator

│ 2024-04-17T22:42:53Z    ERROR    scale_handler    error getting metric spec for the scaler    {"scaledObject.Namespace": "keda", "scaledObject.Name": "keda-add-ons-http-inter │
│ ceptor", "scaler": "externalScaler", "error": "got empty metric spec"}                                                                                                         │
│ github.com/kedacore/keda/v2/pkg/scaling.(*scaleHandler).getScalerState   

### HTTP Add-on Version

0.7.0

### Kubernetes Version

< 1.27

### Platform

Amazon Web Services

**Comment by JorTurFer** [comment]
Hello,
Are the interceptor pods up and running? the scaler pod is restarted when the interceptors are lost

**Comment by JorTurFer** [comment]
I can't reproduce the issue with v0.7.0, but in any case we will cut a release (v0.8.0) during next days, would you be willing to test it once it's released?

**Comment by shreya0910** [comment]
yes sure once v0.8.0 is released, I can try out in dev environment. Thanks
