### ISSUE TITLE
Add documentation on using the interceptor or scaler without other components

### ISSUE THREAD

**Issue by arschles** [kedacore/http-add-on#98]
The operator exists for convenience, and you can use the interceptor or scaler without the other pieces of the puzzle. It would be nice to have documentation on how to do so.

### Use-Case

Some folks might want to use these components in isolation, without the rest of the system, so we should document how to do so

**Comment by tomkerkhove** [comment]
Just curious, when would somebody prefer not to use the operator?

**Comment by arschles** [comment]
I think it's possible that somebody would want to customize their install, and would rather not use the operator to set things up for them. One possibility is if they have a special requirements for traffic routing between their ingress / service mesh infrastructure into the scaling infrastructure.

**Comment by JorTurFer** [comment]
This is done
